const d=document.getElementById("map"),e=document.getElementById("air"),m=document.getElementById("door"),n=document.getElementById("glass"),p=document.getElementById("wall"),q=document.getElementById("liquid"),r=document.getElementById("dummy");let [t,,u]=[!1,!1,document.getElementById("title")];class v{constructor(a,b,c){this.name=a;this.color=b;this.W=c}}function w(a){a=Math.min(Math.max(a,0),255).toString(16).toUpperCase();return 1===a.length?"0"+a:a}
function x(a){a.j.fillStyle="#808080";a.j.fillRect(0,0,32,32);for(let b in a.map)for(let c in a.map[b]){let f=a.I[+a.map[b][c]];isNaN(+c)||0===+a.map[b][c]||(a.j.fillStyle=`#${f.color}`,a.j.fillRect(c,b,1,1))}a.j.fillStyle="#AA8080";a.j.fillRect(15,15,2,2)}
function y(a,{text:b,x:c,y:f,color:h="#FFFFFF",font:g="Carlito",background:k=!1,size:B=16,bold:C=!0,U:D=!1,W:E=!0,X:z=1,$:F=!1}){a.g.font=`${C?"bold ":""}${D?"italic ":""}${B}px ${g}`;k&&(a.g.fillStyle="#00000080",a.g.fillRect(c-("center"==a.g.textAlign?a.g.measureText(b).width/2:0),f-24,a.g.measureText(b).width,28));a.g.fillStyle=h;k=a.g.fillStyle;g="FF";void 0!==k[6]&&void 0!==k[7]&&(g=k[6]+k[7]);if(F){b=[...b];for(l in b)b[l]=0===Math.floor(2*Math.random())?b[l].toUpperCase():b[l].toLowerCase();
var l=b.join("")}else l=b;b=l;E&&(a.g.fillStyle=`#000000${g}`,a.g.fillText(b,c+z,f+z));a.g.fillStyle=h;a.g.fillText(b,c,f)}
function A(){var a=G;t=!0;setInterval(()=>{""===a.s&&(a.s=0===Math.floor(100*Math.random())?"b"+"KeyboardEvent"[(Math.tan(Math.PI/2)+"")[9]]+"bs "+"boolean"[Math.floor(Math.PI/2)]+"l"+(typeof KeyboardEvent)[4+Math.sin(Math.PI/2)]+(typeof Math.PI)[Math.sin(0/Math.PI)]:[...("e"+"null".replace(window.URL.name.toLowerCase().replace("r",""),"i")+(typeof Math.PI)[Math.sin(0/Math.PI)]+"boolean"[Math.floor(Math.PI/2)].toUpperCase()+[..." "].reverse().join("")+"sllaB")].reverse().join(""));a.u=Math.min(Math.max(a.u-
10,0),Infinity);for(let b in a.o)1>a.o[b][3]?a.o.splice(b,1):a.o[b][3]--},50);setInterval(()=>{},5E3);for(let b=0;32>b;b++)a.map.push(["00000000000000000000000000000000"]);x(a);requestAnimationFrame(a.J.bind(a));a.notify({text:"Welcome to the editor!",duration:1E3,color:"DDDDDD",Y:!0})}
class H{constructor(){this.H=this.F=0;this.version="0.1.4";this.h=document.getElementById("ctx");this.g=this.h.getContext("2d");this.map=[];this.I={"-1":{name:"Dummy"},0:new v("Air","808080FF",!1),1:new v("Door","FFFFFF0A",!1),2:new v("Glass","FFFFFF20",!1),3:new v("Wall","AAAAAAFF",!0),4:new v("Liquid","FFFFFF9A",!1)};this.h.map=document.createElement("canvas");this.j=this.h.map.getContext("2d");this.h.map.width=32;this.h.map.height=32;this.j.fillStyle="#808080";this.j.fillRect(0,0,32,32);this.S=
this.h.getBoundingClientRect();this.K=this.S.top;this.h.width=window.innerWidth;this.h.height=window.innerHeight-this.K;this.g.imageSmoothingEnabled=!1;this.G=0;this.keys={shift:16,left:37,Z:38,right:39,T:40,w:87,a:65,V:83,d:68};this.i={};this.D=this.C=this.m=this.l=this.B=this.A=2048;this.M="Lorem ipsum dolor sit amet, and I don't remember the next thing.";this.u=0;this.L="DDDDDD";this.o=[];this.block=3;this.v={O:new Audio("./sound/ChatMessage.ogg"),N:new Audio("./sound/ColorChange.ogg"),R:new Audio("./sound/NameChange.ogg"),
P:new Audio("./sound/Notification.ogg")};this.v.O.pause();this.v.N.pause();this.v.R.pause();this.v.P.pause();this.s="";console.log("%cBalls Online %cEDITOR%c\nAn advanced editor I see, huh? Alright...","font-size: 32px; font-family: 'Carlito'; color: black","font-size: 32px; font-family: 'Carlito'; color: #DDDD00; font-style: italic","");u.innerHTML="Balls Online"}wait(a){return new Promise(b=>setTimeout(b,a))}notify({text:a="Lorem ipsum? Dolor sit amet.",duration:b=1500,color:c="DDDD00",Y:f=!0}){this.M=
a;this.u=b;this.L=c;f&&(new Audio("./sound/Notification.ogg")).play()}J(a){this.G=a-this.H;this.F=1E3/this.G;this.H=a;this.g.textAlign="left";this.g.fillStyle="#AAAAAA";this.g.fillRect(0,0,this.h.width,this.h.height);if(960<=this.h.width&&540<=this.h.height){let [b,c]=[0,0];a=this.G;if(this.i[this.keys.left]||this.i[this.keys.a])b=-a;if(this.i[this.keys.right]||this.i[this.keys.d])b=a;if(this.i[this.keys.Z]||this.i[this.keys.w])c=-a;if(this.i[this.keys.T]||this.i[this.keys.V])c=a;b=0!==c?b/Math.sqrt(2):
b;c=0!==b?c/Math.sqrt(2):c;this.A=Math.min(Math.max(this.A+b,-128),4224);this.B=Math.min(Math.max(this.B+c,-128),4224);this.l=Math.round(this.A);this.m=Math.round(this.B);this.g.drawImage(this.h.map,0,0,32,32,-this.l+this.h.width/2,-this.m+this.h.height/2,4096,4096);for(let f in this.o)a=this.o[f],this.g.fillStyle=`#${a[2]}${w(a[3])}`,this.g.fillRect(a[0]-this.l+this.h.width/2-5.5,a[1]-this.m+this.h.height/2-5.5,10,10);this.g.fillStyle="#FFFFFF";this.g.beginPath();this.g.fillStyle="#FFFFFF";this.g.arc(Math.round(this.C)-
this.l+this.h.width/2,Math.round(this.D)-this.m+this.h.height/2,10,0,2*Math.PI);this.g.fill();this.g.closePath();this.g.textAlign="center";y(this,{text:"Dummy",x:Math.round(this.C)-this.l+this.h.width/2,y:Math.round(this.D)-this.m+this.h.height/2-25,color:"#FFFFFF",font:"Guessy",size:20,X:2});0<this.u&&(this.g.textAlign="center",this.g.fillStyle="#40404080",this.g.fillRect(0,this.h.height-50-25,this.h.width,50),y(this,{text:this.M,x:this.h.width/2,y:this.h.height-50+9,color:"#"+this.L+w(this.u),font:"Guessy",
size:32}));this.g.textAlign="left";y(this,{text:this.s,x:10,y:24,color:"#EEEEEE",size:20});y(this,{text:"EDITOR",x:"Balls Online"===this.s?this.g.measureText("Balls Online").width+15:this.g.measureText(this.s).width+15,y:24,color:"#EEEE00",font:"Guessy",size:20,U:!0,$:0===Math.floor(100*Math.random())?!0:!1});this.g.fillStyle="#BBBBBB";this.g.fillRect(8,30,152,1);y(this,{text:`FPS: ${Math.round(this.F)}`,x:10,y:48,color:30>this.F?15>this.F?"red":"yellow":"lime"});y(this,{text:`Client run: ${Math.floor(performance.now()/
1E3)}s`,x:10,y:80,color:"#AAAAFF"});y(this,{text:`Version: ${this.version}`,x:10,y:112,color:"#AAAAFF"});y(this,{text:`Platform: ${window.navigator.platform}`,x:10,y:128,color:"#AAAAFF"});y(this,{text:`Client res: ${this.h.width}x${this.h.height}`,x:10,y:160,color:"#AAAAFF"});y(this,{text:"Info",x:192,y:24,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(190,30,152,1);y(this,{text:`Camera X: ${Math.round(this.l)}`,x:192,y:48,color:"#DDDDDD"});y(this,{text:`Camera Y: ${Math.round(this.m)}`,
x:192,y:64,color:"#DDDDDD"});y(this,{text:`Dummy X: ${Math.round(this.C)}`,x:192,y:96,color:"#DDDDDD"});y(this,{text:`Dummy Y: ${Math.round(this.D)}`,x:192,y:112,color:"#DDDDDD"});y(this,{text:`Block: ${this.I[this.block].name}`,x:192,y:144,color:"#DDDDDD"})}else this.g.textAlign="left",this.g.fillStyle="#202020",this.g.fillRect(0,0,this.h.width,this.h.height),y(this,{text:"Are you trying to play Balls Online",x:6,y:24,size:24}),y(this,{text:"with such a small resolution?",x:6,y:48,size:24}),y(this,
{text:"Let me tell you something... it's unsupported.",x:6,y:72,size:24}),y(this,{text:"Please use a larger resolution next time you play.",x:6,y:96,size:24}),y(this,{text:"If you're on a phone, try turning it to widescreen.",x:6,y:120,size:24}),y(this,{text:"If you're on a computer, try using fullscreen.",x:6,y:144,size:24}),y(this,{text:`Your resolution is ${this.h.width}x${this.h.height}.`,x:6,y:168,size:24});requestAnimationFrame(this.J.bind(this))}}const G=new H;
window.onresize=()=>{G.h.width=window.innerWidth;G.h.height=window.innerHeight-G.K;G.g.imageSmoothingEnabled=!1};d.addEventListener("click",a=>{a.preventDefault();a=G.h.map.toDataURL("image/png");const b=document.createElement("a");b.href=a;b.download=`editor${Date.now().toString(16)}.png`;b.click();b.remove()});e.addEventListener("click",a=>{a.preventDefault();G.block=0});m.addEventListener("click",a=>{a.preventDefault();G.block=1});n.addEventListener("click",a=>{a.preventDefault();G.block=2});
p.addEventListener("click",a=>{a.preventDefault();G.block=3});q.addEventListener("click",a=>{a.preventDefault();G.block=4});r.addEventListener("click",a=>{a.preventDefault();G.block=-1});window.addEventListener("keydown",a=>G.i[a.keyCode]=!0);window.addEventListener("keyup",a=>G.i[a.keyCode]=!1);
document.addEventListener("click",()=>{t||(document.getElementById("p").remove(),d.removeAttribute("hidden"),e.removeAttribute("hidden"),m.removeAttribute("hidden"),n.removeAttribute("hidden"),p.removeAttribute("hidden"),q.removeAttribute("hidden"),r.removeAttribute("hidden"),A())});
G.h.addEventListener("click",a=>{var b=G.h.getBoundingClientRect(),c=Math.floor(a.clientX-b.left+(G.l-G.h.width/2));a=Math.floor(a.clientY-b.top+(G.m-G.h.height/2));b=G;var f=G.block;const h=Math.floor(c/128),g=Math.floor(a/128);0<=f&&4>=f&&0<=h&&31>=h&&0<=g&&31>=g&&(b.map[g][h]=f,x(b));-1===f&&10<=c&&4086>=c&&10<=a&&4086>=a&&(b.C=c,b.D=a)});
