const d=document.getElementById("map"),e=document.getElementById("air"),m=document.getElementById("door"),n=document.getElementById("glass"),p=document.getElementById("wall"),q=document.getElementById("dummy");let [r,,t]=[!1,!1,document.getElementById("title")];function u(a){a=Math.min(Math.max(a,0),255).toString(16).toUpperCase();return 1===a.length?"0"+a:a}
function v(a){for(let b in a.map)for(let c in a.map[b]){switch(+a.map[b][c]){case 0:a.i.fillStyle="#808080";a.i.fillRect(c,b,1,1);break;case 1:a.i.fillStyle="#858585";a.i.fillRect(c,b,1,1);break;case 2:a.i.fillStyle="#909090";a.i.fillRect(c,b,1,1);break;case 3:a.i.fillStyle="#AAAAAA",a.i.fillRect(c,b,1,1)}a.i.fillStyle="#AA8080";a.i.fillRect(15,15,2,2)}}
function w(a,{text:b,x:c,y:f,color:h="#FFFFFF",font:g="Carlito",background:k=!1,size:z=16,bold:A=!0,P:B=!1,ca:C=!0,Z:x=1,ba:D=!1}){a.g.font=`${A?"bold ":""}${B?"italic ":""}${z}px ${g}`;k&&(a.g.fillStyle="#00000080",a.g.fillRect(c-("center"==a.g.textAlign?a.g.measureText(b).width/2:0),f-24,a.g.measureText(b).width,28));a.g.fillStyle=h;k=a.g.fillStyle;g="FF";void 0!==k[6]&&void 0!==k[7]&&(g=k[6]+k[7]);if(D){b=[...b];for(l in b)b[l]=0===Math.floor(2*Math.random())?b[l].toUpperCase():b[l].toLowerCase();
var l=b.join("")}else l=b;b=l;C&&(a.g.fillStyle=`#000000${g}`,a.g.fillText(b,c+x,f+x));a.g.fillStyle=h;a.g.fillText(b,c,f)}
function y(){var a=E;r=!0;setInterval(()=>{""===a.v&&(a.v=0===Math.floor(100*Math.random())?"b"+"KeyboardEvent"[(Math.tan(Math.PI/2)+"")[9]]+"bs "+"boolean"[Math.floor(Math.PI/2)]+"l"+(typeof KeyboardEvent)[4+Math.sin(Math.PI/2)]+(typeof Math.PI)[Math.sin(0/Math.PI)]:[...("e"+"null".replace(window.URL.name.toLowerCase().replace("r",""),"i")+(typeof Math.PI)[Math.sin(0/Math.PI)]+"boolean"[Math.floor(Math.PI/2)].toUpperCase()+[..." "].reverse().join("")+"sllaB")].reverse().join(""));a.u=Math.min(Math.max(a.u-
10,0),Infinity);for(let b in a.s)1>a.s[b][3]?a.s.splice(b,1):a.s[b][3]--},50);a.I=a.J[0];setInterval(()=>{a.I=a.J[Math.floor(Math.random()*a.J.length)]},5E3);for(let b=0;32>b;b++)a.map.push(["00000000000000000000000000000000"]);v(a);requestAnimationFrame(a.L.bind(a));a.notify({text:"Welcome to the editor!",duration:1E3,color:"DDDDDD",$:!0})}
class F{constructor(){this.K=this.G=0;this.version="0.1.3";this.h=document.getElementById("ctx");this.g=this.h.getContext("2d");this.map=[];this.h.map=document.createElement("canvas");this.i=this.h.map.getContext("2d");this.h.map.width=32;this.h.map.height=32;this.i.fillStyle="#808080";this.i.fillRect(0,0,32,32);this.W=this.h.getBoundingClientRect();this.M=this.W.top;this.h.width=window.innerWidth;this.h.height=window.innerHeight-this.M;this.g.imageSmoothingEnabled=!1;this.H=0;this.keys={shift:16,
left:37,aa:38,right:39,X:40,w:87,a:65,Y:83,d:68};this.j={};this.F=this.D=this.o=this.m=this.C=this.B=2048;this.O="Lorem ipsum dolor sit amet, and I don't remember the next thing.";this.u=0;this.N="DDDDDD";this.s=[];this.l=3;this.V={"-1":"Dummy",0:"Air",1:"Door",2:"Glass",3:"Wall"};this.A={S:new Audio("./sound/ChatMessage.ogg"),R:new Audio("./sound/ColorChange.ogg"),U:new Audio("./sound/NameChange.ogg"),T:new Audio("./sound/Notification.ogg")};this.A.S.pause();this.A.R.pause();this.A.U.pause();this.A.T.pause();
this.J=["Made by dottych","GitHub: dottych","YouTube: dottych","Discord: dottych","Pinto: .ch"];this.I="I like rice.";this.v="";console.log("%cBalls Online %cEDITOR%c\nAn advanced editor I see, huh? Alright...","font-size: 32px; font-family: 'Carlito'; color: black","font-size: 32px; font-family: 'Carlito'; color: #DDDD00; font-style: italic","");t.innerHTML="Balls Online"}wait(a){return new Promise(b=>setTimeout(b,a))}notify({text:a="Lorem ipsum? Dolor sit amet.",duration:b=1500,color:c="DDDD00",
$:f=!0}){this.O=a;this.u=b;this.N=c;f&&(new Audio("./sound/Notification.ogg")).play()}L(a){this.H=a-this.K;this.G=1E3/this.H;this.K=a;this.g.textAlign="left";this.g.fillStyle="#AAAAAA";this.g.fillRect(0,0,this.h.width,this.h.height);if(960<=this.h.width&&540<=this.h.height){let [b,c]=[0,0];a=this.H;if(this.j[this.keys.left]||this.j[this.keys.a])b=-a;if(this.j[this.keys.right]||this.j[this.keys.d])b=a;if(this.j[this.keys.aa]||this.j[this.keys.w])c=-a;if(this.j[this.keys.X]||this.j[this.keys.Y])c=a;
b=0!==c?b/Math.sqrt(2):b;c=0!==b?c/Math.sqrt(2):c;this.B=Math.min(Math.max(this.B+b,-128),4224);this.C=Math.min(Math.max(this.C+c,-128),4224);this.m=Math.round(this.B);this.o=Math.round(this.C);this.g.drawImage(this.h.map,0,0,32,32,-this.m+this.h.width/2,-this.o+this.h.height/2,4096,4096);for(let f in this.s)a=this.s[f],this.g.fillStyle=`#${a[2]}${u(a[3])}`,this.g.fillRect(a[0]-this.m+this.h.width/2-5.5,a[1]-this.o+this.h.height/2-5.5,10,10);this.g.fillStyle="#FFFFFF";this.g.beginPath();this.g.fillStyle=
"#FFFFFF";this.g.arc(Math.round(this.D)-this.m+this.h.width/2,Math.round(this.F)-this.o+this.h.height/2,10,0,2*Math.PI);this.g.fill();this.g.closePath();this.g.textAlign="center";w(this,{text:"Dummy",x:Math.round(this.D)-this.m+this.h.width/2,y:Math.round(this.F)-this.o+this.h.height/2-25,color:"#FFFFFF",font:"Guessy",size:20,Z:2});0<this.u&&(this.g.textAlign="center",this.g.fillStyle="#40404080",this.g.fillRect(0,this.h.height-50-25,this.h.width,50),w(this,{text:this.O,x:this.h.width/2,y:this.h.height-
50+9,color:"#"+this.N+u(this.u),font:"Guessy",size:32}));this.g.textAlign="left";w(this,{text:this.v,x:10,y:24,color:"#EEEEEE",size:20});w(this,{text:"EDITOR",x:"Balls Online"===this.v?this.g.measureText("Balls Online").width+15:this.g.measureText(this.v).width+15,y:24,color:"#EEEE00",font:"Guessy",size:20,P:!0,ba:0===Math.floor(100*Math.random())?!0:!1});this.g.fillStyle="#BBBBBB";this.g.fillRect(8,30,152,1);w(this,{text:`FPS: ${Math.round(this.G)}`,x:10,y:48,color:30>this.G?15>this.G?"red":"yellow":
"lime"});w(this,{text:`Client run: ${Math.floor(performance.now()/1E3)}s`,x:10,y:80,color:"#AAAAFF"});w(this,{text:`Version: ${this.version}`,x:10,y:112,color:"#AAAAFF"});w(this,{text:`Platform: ${window.navigator.platform}`,x:10,y:128,color:"#AAAAFF"});w(this,{text:`Client res: ${this.h.width}x${this.h.height}`,x:10,y:160,color:"#AAAAFF"});w(this,{text:"Info",x:192,y:24,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(190,30,152,1);w(this,{text:`Camera X: ${Math.round(this.m)}`,x:192,
y:48,color:"#DDDDDD"});w(this,{text:`Camera Y: ${Math.round(this.o)}`,x:192,y:64,color:"#DDDDDD"});w(this,{text:`Dummy X: ${Math.round(this.D)}`,x:192,y:96,color:"#DDDDDD"});w(this,{text:`Dummy Y: ${Math.round(this.F)}`,x:192,y:112,color:"#DDDDDD"});w(this,{text:`Element: ${this.V[this.l]}`,x:192,y:144,color:"#DDDDDD"});w(this,{text:this.I,x:192,y:176,color:"#DDDDDD",P:!0})}else this.g.textAlign="left",this.g.fillStyle="#202020",this.g.fillRect(0,0,this.h.width,this.h.height),w(this,{text:"Are you trying to play Balls Online",
x:6,y:24,size:24}),w(this,{text:"with such a small resolution?",x:6,y:48,size:24}),w(this,{text:"Let me tell you something... it's unsupported.",x:6,y:72,size:24}),w(this,{text:"Please use a larger resolution next time you play.",x:6,y:96,size:24}),w(this,{text:"If you're on a phone, try turning it to widescreen.",x:6,y:120,size:24}),w(this,{text:"If you're on a computer, try using fullscreen.",x:6,y:144,size:24}),w(this,{text:`Your resolution is ${this.h.width}x${this.h.height}.`,x:6,y:168,size:24});
requestAnimationFrame(this.L.bind(this))}}const E=new F;window.onresize=()=>{E.h.width=window.innerWidth;E.h.height=window.innerHeight-E.M;E.g.imageSmoothingEnabled=!1};d.addEventListener("click",a=>{a.preventDefault();a=E.h.map.toDataURL("image/png");const b=document.createElement("a");b.href=a;b.download=`editor${Date.now().toString(16)}.png`;b.click();b.remove()});e.addEventListener("click",a=>{a.preventDefault();E.l=0});m.addEventListener("click",a=>{a.preventDefault();E.l=1});
n.addEventListener("click",a=>{a.preventDefault();E.l=2});p.addEventListener("click",a=>{a.preventDefault();E.l=3});q.addEventListener("click",a=>{a.preventDefault();E.l=-1});window.addEventListener("keydown",a=>E.j[a.keyCode]=!0);window.addEventListener("keyup",a=>E.j[a.keyCode]=!1);
document.addEventListener("click",()=>{r||(document.getElementById("p").remove(),d.removeAttribute("hidden"),e.removeAttribute("hidden"),m.removeAttribute("hidden"),n.removeAttribute("hidden"),p.removeAttribute("hidden"),q.removeAttribute("hidden"),y())});
E.h.addEventListener("click",a=>{var b=E.h.getBoundingClientRect(),c=Math.floor(a.clientX-b.left+(E.m-E.h.width/2));a=Math.floor(a.clientY-b.top+(E.o-E.h.height/2));b=E;var f=E.l;const h=Math.floor(c/128),g=Math.floor(a/128);0<=f&&3>=f&&0<=h&&31>=h&&0<=g&&31>=g&&(b.map[g][h]=f,v(b));-1===f&&10<=c&&4086>=c&&10<=a&&4086>=a&&(b.D=c,b.F=a)});
