const b=document.getElementById("map"),e=document.getElementById("air"),l=document.getElementById("door"),m=document.getElementById("glass"),n=document.getElementById("wall"),p=document.getElementById("dummy");let [q,,r]=[!1,!1,document.getElementById("title")];function t(a){a=Math.min(Math.max(a,0),255).toString(16).toUpperCase();return 1===a.length?"0"+a:a}
function u(){var a=v;for(let c in a.map)for(let d in a.map[c]){switch(+a.map[c][d]){case 0:a.i.fillStyle="#808080";a.i.fillRect(d,c,1,1);break;case 1:a.i.fillStyle="#858585";a.i.fillRect(d,c,1,1);break;case 2:a.i.fillStyle="#909090";a.i.fillRect(d,c,1,1);break;case 3:a.i.fillStyle="#AAAAAA",a.i.fillRect(d,c,1,1)}a.i.fillStyle="#AA8080";a.i.fillRect(15,15,2,2)}}
function x(a,{text:c,x:d,y:f,color:g="#FFFFFF",font:h="Carlito",background:k=!1,size:y=16,bold:z=!0,P:A=!1,ba:B=!0,Z:w=1}){a.g.font=`${z?"bold ":""}${A?"italic ":""}${y}px ${h}`;k&&(a.g.fillStyle="#00000080",a.g.fillRect(d-("center"==a.g.textAlign?a.g.measureText(c).width/2:0),f-24,a.g.measureText(c).width,28));a.g.fillStyle=g;h=a.g.fillStyle;k="FF";void 0!==h[6]&&void 0!==h[7]&&(k=h[6]+h[7]);B&&(a.g.fillStyle=`#000000${k}`,a.g.fillText(c,d+w,f+w));a.g.fillStyle=g;a.g.fillText(c,d,f)}
class C{constructor(){this.K=this.G=0;this.version="0.1.2";this.h=document.getElementById("ctx");this.g=this.h.getContext("2d");this.map=[];this.h.map=document.createElement("canvas");this.i=this.h.map.getContext("2d");this.h.map.width=32;this.h.map.height=32;this.i.fillStyle="#808080";this.i.fillRect(0,0,32,32);this.W=this.h.getBoundingClientRect();this.M=this.W.top;this.h.width=window.innerWidth;this.h.height=window.innerHeight-this.M;this.g.imageSmoothingEnabled=!1;this.H=0;this.keys={shift:16,
left:37,aa:38,right:39,X:40,w:87,a:65,Y:83,d:68};this.j={};this.F=this.D=this.o=this.m=this.C=this.B=2048;this.O="Lorem ipsum dolor sit amet, and I don't remember the next thing.";this.u=0;this.N="DDDDDD";this.s=[];this.l=3;this.V={"-1":"Dummy",0:"Air",1:"Door",2:"Glass",3:"Wall"};this.A={S:new Audio("./sound/ChatMessage.ogg"),R:new Audio("./sound/ColorChange.ogg"),U:new Audio("./sound/NameChange.ogg"),T:new Audio("./sound/Notification.ogg")};this.A.S.pause();this.A.R.pause();this.A.U.pause();this.A.T.pause();
this.J=["Made by dottych","GitHub: dottych","YouTube: dottych","Discord: dottych","Pinto: .ch"];this.I="I like rice.";this.v="";console.log("%cBalls Online %cEDITOR%c\nAn advanced editor I see, huh? Alright...","font-size: 32px; font-family: 'Carlito'; color: black","font-size: 32px; font-family: 'Carlito'; color: #DDDD00; font-style: italic","");r.innerHTML="Balls Online"}wait(a){return new Promise(c=>setTimeout(c,a))}notify({text:a="Lorem ipsum? Dolor sit amet.",duration:c=1500,color:d="DDDD00",
$:f=!0}){this.O=a;this.u=c;this.N=d;f&&(new Audio("./sound/Notification.ogg")).play()}L(a){this.H=a-this.K;this.G=1E3/this.H;this.K=a;this.g.textAlign="left";this.g.fillStyle="#AAAAAA";this.g.fillRect(0,0,this.h.width,this.h.height);if(960<=this.h.width&&540<=this.h.height){let [c,d]=[0,0];a=this.H;if(this.j[this.keys.left]||this.j[this.keys.a])c=-a;if(this.j[this.keys.right]||this.j[this.keys.d])c=a;if(this.j[this.keys.aa]||this.j[this.keys.w])d=-a;if(this.j[this.keys.X]||this.j[this.keys.Y])d=a;
c=0!==d?c/Math.sqrt(2):c;d=0!==c?d/Math.sqrt(2):d;this.B=Math.min(Math.max(this.B+c,-128),4224);this.C=Math.min(Math.max(this.C+d,-128),4224);this.m=Math.round(this.B);this.o=Math.round(this.C);this.g.drawImage(this.h.map,0,0,32,32,-this.m+this.h.width/2,-this.o+this.h.height/2,4096,4096);for(let f in this.s)a=this.s[f],this.g.fillStyle=`#${a[2]}${t(a[3])}`,this.g.fillRect(a[0]-this.m+this.h.width/2-5.5,a[1]-this.o+this.h.height/2-5.5,10,10);this.g.fillStyle="#FFFFFF";this.g.beginPath();this.g.fillStyle=
"#FFFFFF";this.g.arc(Math.round(this.D)-this.m+this.h.width/2,Math.round(this.F)-this.o+this.h.height/2,10,0,2*Math.PI);this.g.fill();this.g.closePath();this.g.textAlign="center";x(this,{text:"Dummy",x:Math.round(this.D)-this.m+this.h.width/2,y:Math.round(this.F)-this.o+this.h.height/2-25,color:"#FFFFFF",font:"Guessy",size:20,Z:2});0<this.u&&(this.g.textAlign="center",this.g.fillStyle="#40404080",this.g.fillRect(0,this.h.height-50-25,this.h.width,50),x(this,{text:this.O,x:this.h.width/2,y:this.h.height-
50+9,color:"#"+this.N+t(this.u),font:"Guessy",size:32}));this.g.textAlign="left";x(this,{text:this.v,x:10,y:24,color:"#EEEEEE",size:20});x(this,{text:"EDITOR",x:"Balls Online"===this.v?this.g.measureText("Balls Online").width+15:this.g.measureText(this.v).width+15,y:24,color:"#EEEE00",font:"Guessy",size:20,P:!0});this.g.fillStyle="#BBBBBB";this.g.fillRect(8,30,152,1);x(this,{text:`FPS: ${Math.round(this.G)}`,x:10,y:48,color:30>this.G?15>this.G?"red":"yellow":"lime"});x(this,{text:`Client run: ${Math.floor(performance.now()/
1E3)}s`,x:10,y:80,color:"#AAAAFF"});x(this,{text:`Version: ${this.version}`,x:10,y:112,color:"#AAAAFF"});x(this,{text:`Platform: ${window.navigator.platform}`,x:10,y:128,color:"#AAAAFF"});x(this,{text:`Client res: ${this.h.width}x${this.h.height}`,x:10,y:160,color:"#AAAAFF"});x(this,{text:"Info",x:192,y:24,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(190,30,152,1);x(this,{text:`Camera X: ${Math.round(this.m)}`,x:192,y:48,color:"#DDDDDD"});x(this,{text:`Camera Y: ${Math.round(this.o)}`,
x:192,y:64,color:"#DDDDDD"});x(this,{text:`Dummy X: ${Math.round(this.D)}`,x:192,y:96,color:"#DDDDDD"});x(this,{text:`Dummy Y: ${Math.round(this.F)}`,x:192,y:112,color:"#DDDDDD"});x(this,{text:`Element: ${this.V[this.l]}`,x:192,y:144,color:"#DDDDDD"});x(this,{text:this.I,x:192,y:176,color:"#DDDDDD",P:!0})}else this.g.textAlign="left",this.g.fillStyle="#202020",this.g.fillRect(0,0,this.h.width,this.h.height),x(this,{text:"Are you trying to play Balls Online",x:6,y:24,size:24}),x(this,{text:"with such a small resolution?",
x:6,y:48,size:24}),x(this,{text:"Let me tell you something... it's unsupported.",x:6,y:72,size:24}),x(this,{text:"Please use a larger resolution next time you play.",x:6,y:96,size:24}),x(this,{text:"If you're on a phone, try turning it to widescreen.",x:6,y:120,size:24}),x(this,{text:"If you're on a computer, try using fullscreen.",x:6,y:144,size:24}),x(this,{text:`Your resolution is ${this.h.width}x${this.h.height}.`,x:6,y:168,size:24});requestAnimationFrame(this.L.bind(this))}}const v=new C;
window.onresize=()=>{v.h.width=window.innerWidth;v.h.height=window.innerHeight-v.M;v.g.imageSmoothingEnabled=!1};b.addEventListener("click",a=>{a.preventDefault();a=v.h.map.toDataURL("image/png");const c=document.createElement("a");c.href=a;c.download=`editor${Date.now().toString(16)}.png`;c.click();c.remove()});e.addEventListener("click",a=>{a.preventDefault();v.l=0});l.addEventListener("click",a=>{a.preventDefault();v.l=1});m.addEventListener("click",a=>{a.preventDefault();v.l=2});
n.addEventListener("click",a=>{a.preventDefault();v.l=3});p.addEventListener("click",a=>{a.preventDefault();v.l=-1});window.addEventListener("keydown",a=>v.j[a.keyCode]=!0);window.addEventListener("keyup",a=>v.j[a.keyCode]=!1);
setInterval(()=>{""===v.v&&(v.v=0===Math.floor(100*Math.random())?"b"+"KeyboardEvent"[(Math.tan(Math.PI/2)+"")[9]]+"bs "+"boolean"[Math.floor(Math.PI/2)]+"l"+(typeof KeyboardEvent)[4+Math.sin(Math.PI/2)]+(typeof Math.PI)[Math.sin(0/Math.PI)]:"Balls Online");v.u=Math.min(Math.max(v.u-10,0),Infinity);for(let a in v.s)1>v.s[a][3]?v.s.splice(a,1):v.s[a][3]--},50);v.I=v.J[0];setInterval(()=>{v.I=v.J[Math.floor(Math.random()*v.J.length)]},5E3);
document.addEventListener("click",()=>{if(!q){document.getElementById("p").remove();b.removeAttribute("hidden");e.removeAttribute("hidden");l.removeAttribute("hidden");m.removeAttribute("hidden");n.removeAttribute("hidden");p.removeAttribute("hidden");q=!0;for(let a=0;32>a;a++)v.map.push(["00000000000000000000000000000000"]);u();requestAnimationFrame(v.L.bind(v));v.notify({text:"Welcome to the editor!",duration:1E3,color:"DDDDDD",$:!0})}});
v.h.addEventListener("click",a=>{var c=v.h.getBoundingClientRect(),d=Math.floor(a.clientX-c.left+(v.m-v.h.width/2));a=Math.floor(a.clientY-c.top+(v.o-v.h.height/2));c=v.l;const f=Math.floor(d/128),g=Math.floor(a/128);0<=c&&3>=c&&0<=f&&31>=f&&0<=g&&31>=g&&(v.map[g][f]=c,u());-1===c&&10<=d&&4086>=d&&10<=a&&4086>=a&&(v.D=d,v.F=a)});
