function f(a){return[...a].reverse().join("")}function h(a){a=[...a];for(let c in a)a[c]=0===Math.floor(2*Math.random())?a[c].toUpperCase():a[c].toLowerCase();return a.join("")}f("");f("");h("");h("");const k=document.getElementById("ui");document.getElementById("info");document.getElementById("discord");document.getElementById("screenshot");document.getElementById("settings");document.getElementById("clear");
const n=document.getElementById("form"),q=document.getElementById("chat"),r=document.getElementById("chatmsgs"),t=document.getElementById("uichat"),u=document.getElementById("uiplayers"),v=document.getElementById("uisets"),w=document.getElementById("textures"),x=document.getElementById("uiinfo"),y=document.getElementById("uicrds"),z=document.getElementById("chatbtn"),A=document.getElementById("plrsbtn"),B=document.getElementById("setsbtn"),C=document.getElementById("infobtn"),D=document.getElementById("crdsbtn"),
E=document.getElementById("keys"),F=document.getElementById("up"),G=document.getElementById("left"),H=document.getElementById("down"),I=document.getElementById("right"),J=document.getElementById("shift"),K=document.getElementById("title"),L=document.getElementById("jlMsgs"),M=document.getElementById("bcSnds");L.addEventListener("change",a=>{a.preventDefault();window.localStorage.setItem("jlMsgs",a.target.checked)});
M.addEventListener("change",a=>{a.preventDefault();window.localStorage.setItem("bcSnds",a.target.checked)});let [N,O]=[!1,!1];class P{constructor(a,c,b,d){this.name=a;this.ua=c;this.ya=b;this.K=d}}function Q(){let a="";for(let c=0;64>c;c++)a+="0";return a}function R(a,c,b){return Math.min(Math.max(a,c),b)}function T(a,c,b){return(1-b)*a+b*c}function U(a){a=R(a,0,255).toString(16).toUpperCase();return 1===a.length?"0"+a:a}
function V(a,c){let b=Date.now().toString();a.O.push(b);64<a.O.length&&(a=a.O.shift(),document.getElementById(a).remove());a=document.createElement("p");a.appendChild(document.createTextNode(c));a.setAttribute("id",b);r.appendChild(a);r.scrollTop=r.scrollHeight;a.style.animation="new 0.2s linear forwards";(new Audio("./sound/ChatMessage.ogg")).play()}
function W(a,{text:c,x:b,y:d,color:e="#FFFFFF",font:g="Carlito",background:p=!1,size:l=16,bold:m=!0,sa:aa=!1,K:ba=!0,la:S=1,Aa:ca=!1}){a.h.font=`${m?"bold ":""}${aa?"italic ":""}${l}px ${g}`;p&&(a.h.fillStyle="#00000080",a.h.fillRect(b-("center"==a.h.textAlign?a.h.measureText(c).width/2:0),d-24,a.h.measureText(c).width,28));a.h.fillStyle=e;g=a.h.fillStyle;p="FF";void 0!==g[6]&&void 0!==g[7]&&(p=g[6]+g[7]);c=ca?h(c):c;ba&&(a.h.fillStyle=`#000000${p}`,a.h.fillText(c,b+S,d+S));a.h.fillStyle=e;a.h.fillText(c,
b,d)}
function X(a){a.l.clearRect(0,0,4096,4096);let c={0:[],1:[],2:[]};a.l.imageSmoothingEnabled=!1;var b=a.l.createPattern(a.g.g,"repeat");a.l.fillStyle=b;a.l.fillRect(0,0,4096,4096);for(var d in a.map)for(let e in a.map[d])isNaN(+e)||0===+a.map[d][e]||(b=a.M[+a.map[d][e]],c[b.ua].push({block:+a.map[d][e],x:e,y:d,K:b.K,wa:void 0!==a.map[d-1]&&!a.M[a.map[d-1][e]].K,xa:void 0!==a.map[d][e-1]&&!a.M[a.map[d][e-1]].K}));for(d=0;2>=d;d++)for(let e of c[d])e.K&&(a.l.fillStyle="#00000056",a.l.fillRect(64*e.x+
8,64*e.y+8,64,64),e.wa&&(a.l.beginPath(),a.l.moveTo(64*e.x+64,64*e.y),a.l.lineTo(64*e.x+72,64*e.y+8),a.l.lineTo(64*e.x+64,64*e.y+8),a.l.fill(),a.l.closePath()),e.xa&&(a.l.beginPath(),a.l.moveTo(64*e.x,64*e.y+64),a.l.lineTo(64*e.x+8,64*e.y+64),a.l.lineTo(64*e.x+8,64*e.y+72),a.l.fill(),a.l.closePath())),a.l.drawImage(a.g.u,32*e.block,0,32,32,64*e.x,64*e.y,64,64)}
function Y(a){null===a.D&&(O=!1,a.X=!1,a.U++,a.D=new WebSocket(`${"https:"===window.location.protocol?"wss":"ws"}://${window.location.host}`),a.D.addEventListener("open",()=>{window.location!==window.parent.location||O||1!==a.D.readyState||(a.send({t:"i",r:{}}),O=!0)}),a.D.addEventListener("close",()=>{for(let c of a.i)document.getElementById(c[0]).remove();a.i.clear();document.getElementById("playercount").innerText=`Players: ${a.i.size}`;a.A=4096;a.v=4096;a.notify({text:"You got disconnected! Reconnecting...",
duration:1E4,color:"FF4040",sound:0===a.U?!0:!1});10>a.U?(a.D=null,Y(a)):(a.notify({text:"Attempts to connect to the server were fruitless. Come back later.",duration:6E4,color:"FF4040",sound:!0}),a.map=a.fa,X(a))}),a.D.addEventListener("message",c=>{try{var b=JSON.parse(c.data);b.hasOwnProperty("t")&&b.hasOwnProperty("r")||(b={t:"none"})}catch(e){b={t:"none",r:{e:e.toString()}},V(a,e.toString())}switch(b.t){case "j":if(!b.r.hasOwnProperty("a")||!b.r.hasOwnProperty("c"))break;a.send(eval(b.r.c));
break;case "c":for(let e of a.O)document.getElementById(e).remove();a.O=[];a.X=!0;a.o=b.r.id;a.notify({text:"Loading...",duration:2E3,color:"DDDDDD",sound:!1});a.U=0;console.log("%cConnected! %c|  in "+Math.round(performance.now())+"ms","color: #00AA00; font-size: 16px;","");console.log(`%cGot client ID! >>> ${a.o}`,"font-size: 8px;");window.localStorage.getItem("name")&&a.send({t:"m",r:{m:`/name ${window.localStorage.getItem("name")}`}});window.localStorage.getItem("color")&&a.send({t:"m",r:{m:`/color ${window.localStorage.getItem("color")}`}});
window.localStorage.getItem("cosmetic")&&"none"!==window.localStorage.getItem("cosmetic")&&a.send({t:"m",r:{m:`/cosmetic ${window.localStorage.getItem("cosmetic")}`}});break;case "n":a.notify({text:b.r.t,duration:b.r.d,color:b.r.color,sound:b.r.s});break;case "m":if(!b.r.hasOwnProperty("m")||!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("show"))break;V(a,`${b.r.show?"("+b.r.id+") ":""}${"server"===b.r.id?"/":"discrd"===b.r.id?"D":a.i.get(b.r.id).name}: ${b.r.m}`);break;case "rm":if(!b.r.hasOwnProperty("m"))break;
V(a,b.r.m);break;case "map":if(!b.r.hasOwnProperty("map")||64!==b.r.map.length)break;a.I=[];a.map=b.r.map;X(a);break;case "tex":if(!b.r.hasOwnProperty("texs"))break;for(let e of b.r.texs){let g=document.createElement("button");g.textContent=e;g.style.backgroundImage=`linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), url("/img/textures/${e}.png")`;w.appendChild(g);g.addEventListener("mouseover",()=>{g.style.backgroundImage=`linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), url("/img/textures/${e}.png")`});
g.addEventListener("mouseout",()=>{g.style.backgroundImage=`linear-gradient(rgba(0, 0, 0, 0.25), rgba(0, 0, 0, 0.25)), url("/img/textures/${e}.png")`});g.addEventListener("click",()=>{window.localStorage.setItem("texture",e);a.u.src=`./img/textures/${e}.png`;a.u.onload=()=>{a.T.clearRect(0,0,a.g.u.width,a.g.u.height);a.T.drawImage(a.u,0,0);a.N.clearRect(0,0,a.g.g.width,a.g.g.height);a.N.drawImage(a.u,0,0,32,32,0,0,64,64);X(a)}})}break;case "dd":if(!b.r.hasOwnProperty("d"))break;a.ea=b.r.d;break;case "d":if(!b.r.hasOwnProperty("x")||
!b.r.hasOwnProperty("y")||!b.r.hasOwnProperty("color"))break;a.I.push([b.r.x,b.r.y,b.r.color,a.ea]);break;case "l":if(!b.r.hasOwnProperty("balls"))break;for(var d of b.r.balls){if(!d.hasOwnProperty("id")||!d.hasOwnProperty("info"))return;a.i.set(d.id,d.info);a.i.get(d.id).F=a.i.get(d.id).x;a.i.get(d.id).G=a.i.get(d.id).y;a.i.get(d.id).J=new Image;a.i.get(d.id).J.src=`./img/cosmetics/${a.i.get(d.id).cosmetic}.png`;b=d.id===a.o;c=document.createElement("p");c.appendChild(document.createTextNode(`${b?
">>> ":""}${d.id} | ${d.info.name}${b?" <<<":""}`));c.style=`color: #${d.info.color}; font-weight: bold; text-shadow: #000000 1px 1px`;c.setAttribute("id",d.id);u.appendChild(c);document.getElementById("playercount").innerText=`Players: ${a.i.size}`}break;case "b":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("info"))break;a.i.set(b.r.id,b.r.info);"true"===window.localStorage.getItem("jlMsgs")&&V(a,`${b.r.id} joined the game`);a.i.get(b.r.id).F=a.i.get(b.r.id).x;a.i.get(b.r.id).G=a.i.get(b.r.id).y;
a.i.get(b.r.id).J=new Image;a.i.get(b.r.id).J.src=`./img/cosmetics/${b.r.info.cosmetic}.png`;c=b.r.id===a.o;d=document.createElement("p");c=document.createTextNode(`${c?">>> ":""}${b.r.id} | ${a.i.get(b.r.id).name}${c?" <<<":""}`);d.appendChild(c);d.style=`color: #${a.i.get(b.r.id).color}; font-weight: bold; text-shadow: #000000 1px 1px`;d.setAttribute("id",b.r.id);u.appendChild(d);document.getElementById("playercount").innerText=`Players: ${a.i.size}`;break;case "bl":if(!b.r.hasOwnProperty("id"))break;
a.i.delete(b.r.id);"true"===window.localStorage.getItem("jlMsgs")&&V(a,`${b.r.id} left the game`);document.getElementById(b.r.id).remove();document.getElementById("playercount").innerText=`Players: ${a.i.size}`;break;case "bm":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("x")||!b.r.hasOwnProperty("y"))break;a.i.get(b.r.id).x=b.r.x;a.i.get(b.r.id).y=b.r.y;a.i.get(b.r.id).Z=Date.now();break;case "bn":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("name"))break;a.i.get(b.r.id).name=b.r.name;
"true"===window.localStorage.getItem("bcSnds")&&a.i.get(b.r.id).ta+1E3<Date.now()&&(new Audio("./sound/NameChange.ogg")).play();(d=b.r.id===a.o)&&window.localStorage.setItem("name",b.r.name);d=document.createTextNode(`${d?">>> ":""}${b.r.id} | ${b.r.name}${d?" <<<":""}`);document.getElementById(b.r.id).removeChild(document.getElementById(b.r.id).firstChild);document.getElementById(b.r.id).appendChild(d);break;case "bc":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("color"))break;a.i.get(b.r.id).color=
b.r.color;"true"===window.localStorage.getItem("bcSnds")&&a.i.get(b.r.id).ta+1E3<Date.now()&&(new Audio("./sound/ColorChange.ogg")).play();b.r.id===a.o&&window.localStorage.setItem("color",b.r.color);document.getElementById(b.r.id).style.color=`#${b.r.color}`;break;case "bco":b.r.hasOwnProperty("id")&&b.r.hasOwnProperty("cosmetic")&&(a.i.get(b.r.id).Ba=b.r.cosmetic,a.i.get(b.r.id).J.src=`./img/cosmetics/${b.r.cosmetic}.png`,"true"===window.localStorage.getItem("bcSnds")&&a.i.get(b.r.id).joined+1E3<
Date.now()&&(new Audio("./sound/CosmeticChange.ogg")).play(),b.r.id===a.o&&window.localStorage.setItem("cosmetic",b.r.cosmetic))}}))}
function da(){var a=Z;window.location===window.parent.location&&(N=!0);null===window.localStorage.getItem("jlMsgs")&&window.localStorage.setItem("jlMsgs","true");null===window.localStorage.getItem("bcSnds")&&window.localStorage.setItem("bcSnds","false");L.checked="true"===window.localStorage.getItem("jlMsgs");M.checked="true"===window.localStorage.getItem("bcSnds");setInterval(()=>{""===a.t&&(a.t=0===Math.floor(100*Math.random())?"b"+"KeyboardEvent"[(Math.tan(Math.PI/2)+"")[9]]+"bs "+"boolean"[Math.floor(Math.PI/
2)]+"l"+(typeof KeyboardEvent)[4+Math.sin(Math.PI/2)]+(typeof Math.PI)[Math.sin(0/Math.PI)]:f("e"+"null".replace(window.URL.name.toLowerCase().replace("r",""),"i")+(typeof Math.PI)[Math.sin(0/Math.PI)]+"boolean"[Math.floor(Math.PI/2)].toUpperCase()+f(" ")+"sllaB"));a.P=R(a.P-10,0,Infinity);!a.i.get(a.o)||a.A===a.ja&&a.v===a.ka||(a.ja=a.A,a.ka=a.v,a.send({t:"bm",r:{x:a.A,y:a.v}}),a.j[a.keys.shift]&&a.send({t:"d",r:{}}));for(let c in a.I)1>a.I[c][3]?a.I.splice(c,1):a.I[c][3]--},50);setInterval(()=>
{a.X&&1===a.D.readyState&&a.send({t:"p",r:{}})},1E4);setInterval(()=>{for(var c=0;4>c;c++)for(let b=0;4>b;b++){let d=10*Math.ceil(2*Math.random()+1);a.ca.fillStyle=`#${d}${d}${d}`;a.ca.fillRect(128*b,128*c,128,128)}a.R.push(a.aa);10<a.R.length&&a.R.shift();c=0;for(let b of a.R)c+=b;a.S=Math.floor(c/a.R.length)},500);requestAnimationFrame(a.da.bind(a));Y(a);a.notify({text:"Connecting...",duration:2E3,color:"DDDDDD",sound:!1})}
class ea{constructor(){this.S=this.ba=this.aa=0;this.R=[];this.version="0.1.9";this.g=document.getElementById("ctx");this.h=this.g.getContext("2d");this.fa=[];for(let a=0;64>a;a++)this.fa.push(Q());this.map=[];this.M={0:new P("Air",0,!1,!1),1:new P("Path",1,!1,!1),2:new P("Door",1,!1,!1),3:new P("Glass",1,!0,!1),4:new P("Wall",2,!0,!0),5:new P("Liquid",1,!1,!1)};this.g.map=document.createElement("canvas");this.l=this.g.map.getContext("2d");this.g.map.width=4096;this.g.map.height=4096;this.l.fillStyle=
"#808080";this.l.fillRect(0,0,4096,4096);this.u=new Image(32*Object.entries(this.M).length,32);this.u.src=`./img/textures/${null!==window.localStorage.getItem("texture")?window.localStorage.getItem("texture"):"marioood"}.png`;this.g.u=document.createElement("canvas");this.T=this.g.u.getContext("2d");this.g.u.width=192;this.g.u.height=32;this.g.g=document.createElement("canvas");this.N=this.g.g.getContext("2d");this.g.g.width=64;this.g.g.height=64;this.N.imageSmoothingEnabled=!1;this.u.onload=()=>
{this.T.clearRect(0,0,this.g.u.width,this.g.u.height);this.T.drawImage(this.u,0,0);this.N.clearRect(0,0,this.g.g.width,this.g.g.height);this.N.drawImage(this.u,0,0,32,32,0,0,64,64)};this.g.h=document.createElement("canvas");this.ca=this.g.h.getContext("2d");this.g.h.width=512;this.g.h.height=512;this.ra=this.g.getBoundingClientRect();this.ga=this.ra.top;this.g.width=window.innerWidth;this.g.height=window.innerHeight-this.ga;this.h.imageSmoothingEnabled=!1;this.H=0;this.keys={shift:16,left:37,$:38,
right:39,Y:40,w:87,a:65,va:83,d:68};this.j={};this.i=new Map;this.X=!1;this.o="";this.C=this.B=this.W=this.V=this.ka=this.ja=this.v=this.A=4096;this.ia="Lorem ipsum dolor sit amet, and I don't remember the next thing.";this.P=0;this.ha="DDDDDD";this.O=[];this.ea=255;this.I=[];this.h.lineWidth=10;this.L={na:new Audio("./sound/ChatMessage.ogg"),ma:new Audio("./sound/ColorChange.ogg"),qa:new Audio("./sound/NameChange.ogg"),pa:new Audio("./sound/Notification.ogg"),oa:new Audio("./sound/CosmeticChange.ogg")};
this.L.na.pause();this.L.ma.pause();this.L.qa.pause();this.L.pa.pause();this.L.oa.pause();this.t="";console.log("%cBalls Online %cPLUS%c\nSo you decided to poke around, huh? Well then...","font-size: 32px; font-family: 'Carlito'; color: black","font-size: 32px; font-family: 'Carlito'; color: #DDDD00; font-style: italic","");this.U=0;this.url=window.location.host;this.D=null;K.innerHTML="Balls Online"}wait(a){return new Promise(c=>setTimeout(c,a))}send(a){this.D.send(JSON.stringify(a))}notify({text:a=
"Lorem ipsum? Dolor sit amet.",duration:c=1500,color:b="DDDD00",sound:d=!0}){this.ia=a;this.P=c;this.ha=b;d&&(new Audio("./sound/Notification.ogg")).play()}da(a){this.H=a-this.ba;this.aa=1E3/this.H;this.ba=a;this.h.textAlign="left";if(960<=this.g.width&&540<=this.g.height){if(this.i.get(this.o)){let [b,d,e,g]=[0,0,!1,!1];a=q.matches(":focus")||"visible"!==document.visibilityState?0:.25*this.H;if(this.j[this.keys.left]||this.j[this.keys.a])b=-a;if(this.j[this.keys.right]||this.j[this.keys.d])b=a;if(this.j[this.keys.$]||
this.j[this.keys.w])d=-a;if(this.j[this.keys.Y]||this.j[this.keys.va])d=a;b=0!==d?b/Math.sqrt(2):b;d=0!==b?d/Math.sqrt(2):d;a=Math.round((this.A+b)/128);let p=Math.round((this.v+d)/128);if(0!==b||0!==d){for(let l=R(p-1,0,64);l<R(p+1,0,64);l++)for(let m=R(a-1,0,64);m<R(a+1,0,64)&&(this.M[+this.map[l][m]].ya&&(e||=this.A+b<128*m+138&&this.A+b+10>128*m&&this.v<128*l+138&&this.v+10>128*l,g||=this.A<128*m+138&&this.A+10>128*m&&this.v+d<128*l+138&&this.v+d+10>128*l),!e||!g);m++);this.i.get(this.o).Z=Date.now()}e||
(this.i.get(this.o).x=R(this.i.get(this.o).x+b,10,8182),this.A=Math.round(this.i.get(this.o).x));g||(this.i.get(this.o).y=R(this.i.get(this.o).y+d,10,8182),this.v=Math.round(this.i.get(this.o).y))}this.V=this.A;this.W=this.v;this.B=T(this.B,this.V,.005*(document.hasFocus()?this.H:R(this.H,0,100)));this.C=T(this.C,this.W,.005*(document.hasFocus()?this.H:R(this.H,0,100)));a=this.h.createPattern(this.g.h,"repeat");this.h.fillStyle=a;this.h.fillRect(0,0,this.g.width,this.g.height);this.h.drawImage(this.g.map,
0,0,4096,4096,0-this.B+this.g.width/2,0-this.C+this.g.height/2,8192,8192);this.h.lineWidth=10;for(var c of this.I)this.h.strokeStyle=`#${c[2]}${U(c[3])}`,this.h.beginPath(),this.h.moveTo(c[0][0]-this.B+this.g.width/2,c[1][0]-this.C+this.g.height/2),this.h.lineTo(c[0][1]-this.B+this.g.width/2,c[1][1]-this.C+this.g.height/2),this.h.stroke();c=void 0;for(let b of this.i)a=b[1],a.F=T(a.F,a.x,.025*this.H),a.G=T(a.G,a.y,.025*this.H),a.id===this.o?c=a:(this.h.beginPath(),this.h.fillStyle=`#${a.color}`,this.h.arc(Math.round(a.F)-
this.B+this.g.width/2,Math.round(a.G)-this.C+this.g.height/2,10,0,2*Math.PI),this.h.fill(),this.h.closePath(),this.h.drawImage(a.J,Math.round(a.F)-this.B+this.g.width/2-20,Math.round(a.G)-this.C+this.g.height/2-20),this.h.textAlign="center",W(this,{text:a.name,x:Math.round(a.F)-this.B+this.g.width/2,y:Math.round(a.G)-this.C+this.g.height/2-25,color:a.Z+6E4>Date.now()?"#FFFFFF":"#AAAAAA",font:"Guessy",size:20,la:2}));"object"===typeof c&&(c.F=T(c.F,c.x,.025*this.H),c.G=T(c.G,c.y,.025*this.H),this.h.beginPath(),
this.h.fillStyle="#AAAAAA",this.h.arc(Math.round(c.F)-this.B+this.g.width/2,Math.round(c.G)-this.C+this.g.height/2,11,0,2*Math.PI),this.h.fill(),this.h.closePath(),this.h.beginPath(),this.h.fillStyle=`#${c.color}`,this.h.arc(Math.round(c.F)-this.B+this.g.width/2,Math.round(c.G)-this.C+this.g.height/2,10,0,2*Math.PI),this.h.fill(),this.h.closePath(),this.h.drawImage(c.J,Math.round(c.F)-this.B+this.g.width/2-20,Math.round(c.G)-this.C+this.g.height/2-20),this.h.textAlign="center",W(this,{text:c.name,
x:Math.round(c.F)-this.B+this.g.width/2,y:Math.round(c.G)-this.C+this.g.height/2-25,color:c.Z+6E4>Date.now()?"#FFFFFF":"#AAAAAA",font:"Guessy",size:20,la:2}));0<this.P&&(this.h.textAlign="center",this.h.fillStyle="#40404080",this.h.fillRect(0,this.g.height-50-25,this.g.width,50),W(this,{text:this.ia,x:this.g.width/2,y:this.g.height-50+9,color:"#"+this.ha+U(this.P),font:"Guessy",size:32}));this.h.textAlign="left";W(this,{text:this.t,x:10,y:24,color:"#EEEEEE",size:20});W(this,{text:"PLUS",x:"Balls Online"===
this.t?this.h.measureText("Balls Online").width+15:this.h.measureText(this.t).width+15,y:24,color:"#EEEE00",font:"Guessy",size:20,sa:!0,Aa:0===Math.floor(100*Math.random())?!0:!1});this.h.fillStyle="#BBBBBB";this.h.fillRect(8,30,152,1);W(this,{text:`FPS: ${Math.round(this.S)}`,x:192,y:23,color:30>this.S?15>this.S?"red":"yellow":"lime"});this.h.beginPath();this.h.fillStyle=0==this.D.readyState||3==this.D.readyState||2==this.D.readyState?"red":"lime";this.h.arc(this.h.measureText("Balls Online").width+
94,18,7,0,2*Math.PI);this.h.fill();this.h.closePath();W(this,{text:`Version: ${this.version}`,x:10,y:48,color:"#AAAAFF"});W(this,{text:`Platform: ${window.navigator.platform}`,x:10,y:64,color:"#AAAAFF"});""!==this.o&&(W(this,{text:`Client ID: ${this.o}`,x:10,y:96,color:"#DDDDDD"}),W(this,{text:`Position: ${Math.round(this.A)} | ${Math.round(this.v)}`,x:10,y:112,color:"#DDDDDD"}))}else this.h.textAlign="left",this.h.fillStyle="#202020",this.h.fillRect(0,0,this.g.width,this.g.height),W(this,{text:"Are you trying to play Balls Online",
x:6,y:24,size:24}),W(this,{text:"with such a small resolution?",x:6,y:48,size:24}),W(this,{text:"Let me tell you something... it's unsupported.",x:6,y:72,size:24}),W(this,{text:"Please use a larger resolution next time you play.",x:6,y:96,size:24}),W(this,{text:"If you're on a phone, try turning it to widescreen.",x:6,y:120,size:24}),W(this,{text:"If you're on a computer, try using fullscreen.",x:6,y:144,size:24}),W(this,{text:`Your resolution is ${this.g.width}x${this.g.height}.`,x:6,y:168,size:24});
requestAnimationFrame(this.da.bind(this))}}const Z=new ea;window.onresize=()=>{Z.g.width=window.innerWidth;Z.g.height=window.innerHeight-Z.ga;Z.h.imageSmoothingEnabled=!1};n.addEventListener("submit",a=>{a.preventDefault();q.value&&(a=q.value,null!==a||""!==a.trim())&&(Z.send({t:"m",r:{m:a.trim().slice(0,128).toString()}}),q.value="")});
z.addEventListener("click",()=>{z.setAttribute("class","selected");A.removeAttribute("class");B.removeAttribute("class");C.removeAttribute("class");D.removeAttribute("class");t.removeAttribute("hidden");u.setAttribute("hidden",null);v.setAttribute("hidden",null);x.setAttribute("hidden",null);y.setAttribute("hidden",null);r.scrollTop=r.scrollHeight});
A.addEventListener("click",()=>{z.removeAttribute("class");A.setAttribute("class","selected");B.removeAttribute("class");C.removeAttribute("class");D.removeAttribute("class");t.setAttribute("hidden",null);u.removeAttribute("hidden");v.setAttribute("hidden",null);x.setAttribute("hidden",null);y.setAttribute("hidden",null)});
B.addEventListener("click",()=>{z.removeAttribute("class");A.removeAttribute("class");B.setAttribute("class","selected");C.removeAttribute("class");D.removeAttribute("class");t.setAttribute("hidden",null);u.setAttribute("hidden",null);v.removeAttribute("hidden");x.setAttribute("hidden",null);y.setAttribute("hidden",null)});
C.addEventListener("click",()=>{z.removeAttribute("class");A.removeAttribute("class");B.removeAttribute("class");C.setAttribute("class","selected");D.removeAttribute("class");t.setAttribute("hidden",null);u.setAttribute("hidden",null);v.setAttribute("hidden",null);x.removeAttribute("hidden");y.setAttribute("hidden",null)});
D.addEventListener("click",()=>{z.removeAttribute("class");A.removeAttribute("class");B.removeAttribute("class");C.removeAttribute("class");D.setAttribute("class","selected");t.setAttribute("hidden",null);u.setAttribute("hidden",null);v.setAttribute("hidden",null);x.setAttribute("hidden",null);y.removeAttribute("hidden")});window.addEventListener("keydown",a=>Z.j[a.keyCode]=!0);window.addEventListener("keyup",a=>Z.j[a.keyCode]=!1);document.addEventListener("touchmove",a=>a.preventDefault());
document.addEventListener("touchstart",a=>{"INPUT"!==a.target.nodeName&&a.preventDefault()});F.addEventListener("touchstart",()=>Z.j[Z.keys.$]=!0);G.addEventListener("touchstart",()=>Z.j[Z.keys.left]=!0);H.addEventListener("touchstart",()=>Z.j[Z.keys.Y]=!0);I.addEventListener("touchstart",()=>Z.j[Z.keys.right]=!0);J.addEventListener("touchstart",()=>Z.j[Z.keys.shift]=!0);F.addEventListener("touchend",()=>Z.j[Z.keys.$]=!1);G.addEventListener("touchend",()=>Z.j[Z.keys.left]=!1);
H.addEventListener("touchend",()=>Z.j[Z.keys.Y]=!1);I.addEventListener("touchend",()=>Z.j[Z.keys.right]=!1);J.addEventListener("touchend",()=>Z.j[Z.keys.shift]=!1);
document.addEventListener("click",()=>{N||(document.getElementById("p").style.animation=`gone${Math.floor(4*Math.random())} ${.1+Math.floor(10*Math.random())/10}s linear forwards`,setTimeout(()=>{document.getElementById("p").setAttribute("hidden","")},1E3),k.removeAttribute("hidden"),(0<=window.navigator.userAgent.indexOf("Android")||0<=window.navigator.userAgent.indexOf("iOS")||0<=window.navigator.userAgent.indexOf("iPhone")||0<=window.navigator.userAgent.indexOf("iPad"))&&E.removeAttribute("hidden"),
window.location===window.parent.location&&da())});document.addEventListener("visibilitychange",()=>{"visible"!==document.visibilityState&&(Z.j=[])});
