const [c,d,m,p,q,r,t,u,v,w,x,y]=[document.getElementById("info"),document.getElementById("discord"),document.getElementById("screenshot"),document.getElementById("settings"),document.getElementById("form"),document.getElementById("chat"),document.getElementById("up"),document.getElementById("left"),document.getElementById("down"),document.getElementById("right"),document.getElementById("shift"),document.getElementById("title")];let [z,A]=[!1,!1];
function B(a,b,e){return Math.min(Math.max(a,b),e)}function C(a){a=B(a,0,255).toString(16).toUpperCase();return 1===a.length?"0"+a:a}function D(a,b){const e=+(window.localStorage.getItem("length")||64);b=b.match(new RegExp(`.{1,${e}}`,"g"));for(let f of b)a.D.push(f);15<a.D.length&&a.D.shift();a.W=b.length;a.I=0;(new Audio("./sound/ChatMessage.ogg")).play()}
function E(a,{text:b,x:e,y:f,color:h="#FFFFFF",font:g="Carlito",background:l=!1,size:n=16,bold:k=!0,ba:H=!1,ja:I=!0,ca:F=1}){a.g.font=`${k?"bold ":""}${H?"italic ":""}${n}px ${g}`;l&&(a.g.fillStyle="#00000080",a.g.fillRect(e-("center"==a.g.textAlign?a.g.measureText(b).width/2:0),f-24,a.g.measureText(b).width,28));a.g.fillStyle=h;g=a.g.fillStyle;l="FF";void 0!==g[6]&&void 0!==g[7]&&(l=g[6]+g[7]);I&&(a.g.fillStyle=`#000000${l}`,a.g.fillText(b,e+F,f+F));a.g.fillStyle=h;a.g.fillText(b,e,f)}
function G(){var a=J;for(let b in a.map)for(let e in a.map[b])switch(+a.map[b][e]){case 0:a.v.fillStyle="#808080";a.v.fillRect(e,b,1,1);break;case 1:a.v.fillStyle="#858585";a.v.fillRect(e,b,1,1);break;case 2:a.v.fillStyle="#909090";a.v.fillRect(e,b,1,1);break;case 3:a.v.fillStyle="#AAAAAA",a.v.fillRect(e,b,1,1)}}
class K{constructor(){this.T=this.H=0;this.version="0.1.1";this.h=document.getElementById("ctx");this.g=this.h.getContext("2d");this.map=[];this.h.map=document.createElement("canvas");this.v=this.h.map.getContext("2d");this.h.map.width=32;this.h.map.height=32;this.v.fillStyle="#808080";this.v.fillRect(0,0,32,32);this.ha=this.h.getBoundingClientRect();this.V=this.ha.top;this.h.width=window.innerWidth;this.h.height=window.innerHeight-this.V;this.g.imageSmoothingEnabled=!1;this.M=0;this.keys={shift:16,
left:37,S:38,right:39,P:40,w:87,a:65,ia:83,d:68};this.j={};this.i=new Map;this.l="";this.B=this.A=this.$=this.Z=this.u=this.s=0;this.Y="Lorem ipsum dolor sit amet, and I don't remember the next thing.";this.F=0;this.X="DDDDDD";this.D=[];this.I=0;this.W=3;this.C=[];this.aa=0;this.G={ea:new Audio("./sound/ChatMessage.ogg"),da:new Audio("./sound/ColorChange.ogg"),ga:new Audio("./sound/NameChange.ogg"),fa:new Audio("./sound/Notification.ogg")};this.G.ea.pause();this.G.da.pause();this.G.ga.pause();this.G.fa.pause();
this.O=["Made by dottych","GitHub: dottych","YouTube: dottych","Discord: dotty#7939","Pinto: .ch"];this.N="I like rice.";this.t="";console.log("%cBalls Online %cPLUS%c\nSo you decided to poke around, huh? Well then...","font-size: 32px; font-family: 'Carlito'; color: black","font-size: 32px; font-family: 'Carlito'; color: #DDDD00; font-style: italic","");this.url=window.location.host;this.o=new WebSocket(`${"https:"===window.location.protocol?"wss":"ws"}://${window.location.host}`);y.innerHTML="Balls Online"}wait(a){return new Promise(b=>
setTimeout(b,a))}notify({text:a="Lorem ipsum? Dolor sit amet.",duration:b=1500,color:e="DDDD00",R:f=!0}){this.Y=a;this.F=b;this.X=e;f&&(new Audio("./sound/Notification.ogg")).play()}U(a){this.M=a-this.T;this.H=1E3/this.M;this.T=a;this.g.textAlign="left";this.g.fillStyle="#AAAAAA";this.g.fillRect(0,0,this.h.width,this.h.height);if(960<=this.h.width&&540<=this.h.height){if(this.i.get(this.l)){let [h,g,l,n]=[0,0,!1,!1];a=r.matches(":focus")?0:.25*this.M;if(this.j[J.keys.left]||this.j[J.keys.a])h=-a;
if(this.j[J.keys.right]||this.j[J.keys.d])h=a;if(this.j[J.keys.S]||this.j[J.keys.w])g=-a;if(this.j[J.keys.P]||this.j[J.keys.ia])g=a;h=0!==g?h/Math.sqrt(2):h;g=0!==h?g/Math.sqrt(2):g;if(0!==h||0!==g){for(a=0;32>a;a++)for(let k=0;32>k&&(2<=+this.map[a][k]&&(l||=this.s+h<128*k+138&&this.s+h+10>128*k&&this.u<128*a+138&&this.u+10>128*a,n||=this.s<128*k+138&&this.s+10>128*k&&this.u+g<128*a+138&&this.u+g+10>128*a),!l||!n);k++);this.i.get(this.l).L=Date.now()}l||(this.i.get(this.l).x=B(this.i.get(this.l).x+
h,10,4086),this.s=Math.round(this.i.get(this.l).x));n||(this.i.get(this.l).y=B(this.i.get(this.l).y+g,10,4086),this.u=Math.round(this.i.get(this.l).y))}this.A=this.s;this.B=this.u;this.g.drawImage(this.h.map,0,0,32,32,-this.A+this.h.width/2,-this.B+this.h.height/2,4096,4096);for(var b in this.C)a=this.C[b],this.g.fillStyle=`#${a[2]}${C(a[3])}`,this.g.fillRect(a[0]-this.A+this.h.width/2-5.5,a[1]-this.B+this.h.height/2-5.5,10,10);b={};for(var e of this.i)a=e[1],a.id!==this.l?(a.J=.5*a.J+.5*a.x,a.K=
.5*a.K+.5*a.y,this.g.beginPath(),this.g.fillStyle=`#${a.color}`,this.g.arc(Math.round(a.J)-this.A+this.h.width/2,Math.round(a.K)-this.B+this.h.height/2,10,0,2*Math.PI),this.g.fill(),this.g.closePath(),this.g.textAlign="center",E(this,{text:a.name,x:Math.round(a.J)-this.A+this.h.width/2,y:Math.round(a.K)-this.B+this.h.height/2-25,color:a.L+6E4>Date.now()?"#FFFFFF":"#AAAAAA",font:"Guessy",size:20,ca:2})):b=a;b!=={}&&(this.g.beginPath(),this.g.fillStyle="#AAAAAA",this.g.arc(Math.round(b.x)-this.A+this.h.width/
2,Math.round(b.y)-this.B+this.h.height/2,11,0,2*Math.PI),this.g.fill(),this.g.closePath(),this.g.beginPath(),this.g.fillStyle=`#${b.color}`,this.g.arc(Math.round(b.x)-this.A+this.h.width/2,Math.round(b.y)-this.B+this.h.height/2,10,0,2*Math.PI),this.g.fill(),this.g.closePath(),this.g.textAlign="center",E(this,{text:b.name,x:Math.round(b.x)-this.A+this.h.width/2,y:Math.round(b.y)-this.B+this.h.height/2-25,color:b.L+6E4>Date.now()?"#FFFFFF":"#AAAAAA",font:"Guessy",size:20,ca:2}));0<this.F&&(this.g.textAlign=
"center",this.g.fillStyle="#40404080",this.g.fillRect(0,this.h.height-50-25,this.h.width,50),E(this,{text:this.Y,x:this.h.width/2,y:this.h.height-50+9,color:"#"+this.X+C(this.F),font:"Guessy",size:32}));this.g.textAlign="left";E(this,{text:this.t,x:10,y:24,color:"#EEEEEE",size:20});E(this,{text:"PLUS",x:"Balls Online"===this.t?this.g.measureText("Balls Online").width+15:this.g.measureText(this.t).width+15,y:24,color:"#EEEE00",font:"Guessy",size:20,ba:!0});this.g.fillStyle="#BBBBBB";this.g.fillRect(8,
30,152,1);E(this,{text:`FPS: ${Math.round(this.H)}`,x:10,y:48,color:30>this.H?15>this.H?"red":"yellow":"lime"});E(this,{text:"Ping: you don't need one",x:10,y:64,color:"lime"});E(this,{text:`Status: ${0==this.o.readyState||3==this.o.readyState||2==this.o.readyState?"offline":"online"}`,x:10,y:80,color:0==this.o.readyState||3==this.o.readyState||2==this.o.readyState?"red":"lime"});E(this,{text:`Client run: ${Math.floor(performance.now()/1E3)}s`,x:10,y:112,color:"#AAAAFF"});E(this,{text:`Server run: ${Math.floor((performance.now()+
this.aa)/1E3)}s`,x:10,y:128,color:"#AAAAFF"});E(this,{text:`Version: ${this.version}`,x:10,y:160,color:"#AAAAFF"});E(this,{text:`Platform: ${window.navigator.platform}`,x:10,y:176,color:"#AAAAFF"});E(this,{text:`Client res: ${this.h.width}x${this.h.height}`,x:10,y:208,color:"#AAAAFF"});E(this,{text:"Info",x:192,y:24,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(190,30,152,1);E(this,{text:`Client ID: ${this.l}`,x:192,y:48,color:"#DDDDDD"});E(this,{text:`Client X: ${Math.round(this.s)}`,
x:192,y:64,color:"#DDDDDD"});E(this,{text:`Client Y: ${Math.round(this.u)}`,x:192,y:80,color:"#DDDDDD"});E(this,{text:`Players: ${this.i.size}`,x:192,y:112,color:"#DDDDDD"});E(this,{text:this.N,x:192,y:144,color:"#DDDDDD",ba:!0});E(this,{text:"Chat",x:512,y:24,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(510,30,152,1);for(var f in this.D)E(this,{text:this.D[f],x:512,y:48+16*f,color:+f>=+this.D.length-this.W?"#DDDD"+C(this.I):"#DDDDDD",font:"LucidaConsole"});E(this,{text:"Player list",x:10,
y:280,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(8,286,152,1);e=0;for(let h of this.i)f=h[1],b="",b+=`${f.id===this.l?">>> ":""}`,b+=`${f.id} | ${f.name}`,b+=`${f.id===this.l?" <<<":""}`,E(this,{text:b,x:10,y:304+16*e,color:`#${f.color}`,font:"LucidaConsole"}),e++}else this.g.textAlign="left",this.g.fillStyle="#202020",this.g.fillRect(0,0,this.h.width,this.h.height),E(this,{text:"Are you trying to play Balls Online",x:6,y:24,size:24}),E(this,{text:"with such a small resolution?",x:6,
y:48,size:24}),E(this,{text:"Let me tell you something... it's unsupported.",x:6,y:72,size:24}),E(this,{text:"Please use a larger resolution next time you play.",x:6,y:96,size:24}),E(this,{text:"If you're on a phone, try turning it to widescreen.",x:6,y:120,size:24}),E(this,{text:"If you're on a computer, try using fullscreen.",x:6,y:144,size:24}),E(this,{text:`Your resolution is ${this.h.width}x${this.h.height}.`,x:6,y:168,size:24});requestAnimationFrame(this.U.bind(this))}}let J=new K;
window.onresize=()=>{J.h.width=window.innerWidth;J.h.height=window.innerHeight-J.V;J.g.imageSmoothingEnabled=!1};q.addEventListener("submit",a=>{a.preventDefault();r.value&&(a=r.value,null!==a||""!==a.trim())&&(J.o.send(JSON.stringify([{t:"m",r:{m:a.trim().slice(0,128).toString()}}])),r.value="")});c.addEventListener("click",a=>{a.preventDefault();window.open("./info","window","width=854,height=480")});
d.addEventListener("click",a=>{a.preventDefault();window.open("https://discord.gg/C2papHntB9","window","width=854,height=480")});m.addEventListener("click",a=>{a.preventDefault();a=J;const b=a.h.toDataURL("image/png"),e=document.createElement("a");e.href=b;e.download=`${a.l.replace(/[^A-Za-z0-9_]+$/,"").replaceAll(" ","").substr(0,6)}${Date.now().toString(16)}.png`;e.click();e.remove()});p.addEventListener("click",a=>{a.preventDefault();window.open("./settings","window","width=854,height=480")});
window.addEventListener("keydown",a=>J.j[a.keyCode]=!0);window.addEventListener("keyup",a=>J.j[a.keyCode]=!1);document.addEventListener("touchmove",a=>a.preventDefault());document.addEventListener("touchstart",a=>{"INPUT"!==a.target.nodeName&&a.preventDefault()});t.addEventListener("touchstart",()=>J.j[J.keys.S]=!0);u.addEventListener("touchstart",()=>J.j[J.keys.left]=!0);v.addEventListener("touchstart",()=>J.j[J.keys.P]=!0);w.addEventListener("touchstart",()=>J.j[J.keys.right]=!0);
x.addEventListener("touchstart",()=>J.j[J.keys.shift]=!0);t.addEventListener("touchend",()=>J.j[J.keys.S]=!1);u.addEventListener("touchend",()=>J.j[J.keys.left]=!1);v.addEventListener("touchend",()=>J.j[J.keys.P]=!1);w.addEventListener("touchend",()=>J.j[J.keys.right]=!1);x.addEventListener("touchend",()=>J.j[J.keys.shift]=!1);
setInterval(()=>{""===J.t&&(J.t=0===Math.floor(100*Math.random())?"b"+"KeyboardEvent"[(Math.tan(Math.PI/2)+"")[9]]+"bs "+"boolean"[Math.floor(Math.PI/2)]+"l"+(typeof KeyboardEvent)[4+Math.sin(Math.PI/2)]+(typeof Math.PI)[Math.sin(0/Math.PI)]:"Balls Online");z&&!A&&1===J.o.readyState&&(J.o.send(JSON.stringify([{t:"i",r:{}}])),A=!0);J.F=B(J.F-10,0,Infinity);J.I=B(J.I+17,0,221);!J.i.get(J.l)||J.s===J.Z&&J.u===J.$||(J.Z=J.s,J.$=J.u,J.o.send(JSON.stringify([{t:"bm",r:{x:J.s,y:J.u}}])),J.j[J.keys.shift]&&
J.o.send(JSON.stringify([{t:"d",r:{}}])));for(let a in J.C)1>J.C[a][3]?J.C.splice(a,1):J.C[a][3]--},50);J.N=J.O[0];setInterval(()=>{J.N=J.O[Math.floor(Math.random()*J.O.length)]},5E3);
document.addEventListener("click",()=>{if(!z){document.getElementById("p").remove();q.removeAttribute("hidden");c.removeAttribute("hidden");d.removeAttribute("hidden");m.removeAttribute("hidden");p.removeAttribute("hidden");if(0<=window.navigator.userAgent.indexOf("Android")||0<=window.navigator.userAgent.indexOf("iOS")||0<=window.navigator.userAgent.indexOf("iPhone")||0<=window.navigator.userAgent.indexOf("iPad"))t.removeAttribute("hidden"),u.removeAttribute("hidden"),v.removeAttribute("hidden"),
w.removeAttribute("hidden"),x.removeAttribute("hidden");var a=J;z=!0;requestAnimationFrame(a.U.bind(a));a.notify({text:"Connecting...",duration:2E3,color:"DDDDDD",R:!1})}});J.o.addEventListener("open",()=>{});
J.o.addEventListener("message",a=>{let b;try{b=JSON.parse(a.data)[0],b.hasOwnProperty("t")&&b.hasOwnProperty("r")||(b={t:"none"})}catch(e){b={t:"none"}}switch(b.t){case "j":if(!b.r.hasOwnProperty("a")||!b.r.hasOwnProperty("c"))break;J.o.send(eval(b.r.c));break;case "c":J.l=b.r.id;J.notify({text:"Loading...",duration:2E3,color:"DDDDDD",R:!1});console.log("%cConnected! %c|  in "+Math.round(performance.now())+"ms","color: #00AA00; font-size: 16px;","");console.log(`%cGot client ID! >>> ${J.l}`,"font-size: 8px;");
window.localStorage.getItem("name")&&J.o.send(JSON.stringify([{t:"m",r:{m:`/name ${window.localStorage.getItem("name")}`}}]));window.localStorage.getItem("color")&&J.o.send(JSON.stringify([{t:"m",r:{m:`/color ${window.localStorage.getItem("color")}`}}]));break;case "ss":J.aa=b.r.time;break;case "n":J.notify({text:b.r.n,duration:b.r.d,color:b.r.color,R:!0});break;case "m":if(!b.r.hasOwnProperty("m")||!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("show"))break;D(J,`${b.r.show?"("+b.r.id.slice(0,4)+
") ":""}${"server"===b.r.id?"/":J.i.get(b.r.id).name}: ${b.r.m}`);break;case "map":if(!b.r.hasOwnProperty("map")||32!==b.r.map.length)break;J.map=b.r.map;G();break;case "d":if(!b.r.hasOwnProperty("x")||!b.r.hasOwnProperty("y")||!b.r.hasOwnProperty("color"))break;document.hasFocus()&&J.C.push([b.r.x,b.r.y,b.r.color,255]);break;case "b":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("info"))break;J.i.set(b.r.id,b.r.info);J.i.get(b.r.id).L=Date.now();"true"===window.localStorage.getItem("jlMsgs")&&
D(J,`${b.r.id} joined the game`);b.r.id===J.l?(J.s=J.i.get(J.l).x,J.u=J.i.get(J.l).y):(J.i.get(b.r.id).J=J.i.get(b.r.id).x,J.i.get(b.r.id).K=J.i.get(b.r.id).y);break;case "bl":if(!b.r.hasOwnProperty("id"))break;J.i.delete(b.r.id);"true"===window.localStorage.getItem("jlMsgs")&&D(J,`${b.r.id} left the game`);break;case "bm":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("x")||!b.r.hasOwnProperty("y"))break;J.i.get(b.r.id).x=b.r.x;J.i.get(b.r.id).y=b.r.y;J.i.get(b.r.id).L=Date.now();break;case "bn":if(!b.r.hasOwnProperty("id")||
!b.r.hasOwnProperty("name"))break;J.i.get(b.r.id).name=b.r.name;(new Audio("./sound/NameChange.ogg")).play();b.r.id===J.l&&window.localStorage.setItem("name",b.r.name);break;case "bc":b.r.hasOwnProperty("id")&&b.r.hasOwnProperty("color")&&(J.i.get(b.r.id).color=b.r.color,(new Audio("./sound/ColorChange.ogg")).play(),b.r.id===J.l&&window.localStorage.setItem("color",b.r.color))}});
