function c(a){return[...a].reverse().join("")}function e(a){a=[...a];for(let b in a)a[b]=0===Math.floor(2*Math.random())?a[b].toUpperCase():a[b].toLowerCase();return a.join("")}c("");c("");e("");e("");
const [k,l,q,r,t,v,w,y,z,A,B,C,D]=[document.getElementById("info"),document.getElementById("discord"),document.getElementById("screenshot"),document.getElementById("settings"),document.getElementById("clear"),document.getElementById("form"),document.getElementById("chat"),document.getElementById("up"),document.getElementById("left"),document.getElementById("down"),document.getElementById("right"),document.getElementById("shift"),document.getElementById("title")];let [E,F]=[!1,!1];
class G{constructor(a,b,d,f){this.name=a;this.color=b;this.qa=d;this.ha=f}}function H(a,b,d){return Math.min(Math.max(a,b),d)}function I(a,b,d){return(1-d)*a+d*b}function J(a){a=H(a,0,255).toString(16).toUpperCase();return 1===a.length?"0"+a:a}function K(a,b){a.v.send(JSON.stringify([b]))}
function L(a){var b=M;const d=+(window.localStorage.getItem("length")||64);a=a.match(new RegExp(`.{1,${d}}`,"g"));for(let f of a)b.G.push(f),18<b.G.length&&b.G.shift();b.ba=a.length;b.N=0;(new Audio("./sound/ChatMessage.ogg")).play()}
function O(a,{text:b,x:d,y:f,color:h="#FFFFFF",font:g="Carlito",background:p=!1,size:u=16,bold:x=!0,oa:m=!1,ha:n=!0,ia:N=1,ra:P=!1}){a.g.font=`${x?"bold ":""}${m?"italic ":""}${u}px ${g}`;p&&(a.g.fillStyle="#00000080",a.g.fillRect(d-("center"==a.g.textAlign?a.g.measureText(b).width/2:0),f-24,a.g.measureText(b).width,28));a.g.fillStyle=h;g=a.g.fillStyle;p="FF";void 0!==g[6]&&void 0!==g[7]&&(p=g[6]+g[7]);b=P?e(b):b;n&&(a.g.fillStyle=`#000000${p}`,a.g.fillText(b,d+N,f+N));a.g.fillStyle=h;a.g.fillText(b,
d,f)}function Q(){var a=M;a.D.fillStyle="#808080";a.D.fillRect(0,0,256,256);a.D.fillStyle="#00000010";a.D.fillRect(0,0,256,1);a.D.fillRect(0,1,1,255);for(let b in a.map)for(let d in a.map[b]){let f=a.X[+a.map[b][d]];isNaN(+d)||0===+a.map[b][d]||(f.ha&&(a.D.fillStyle="#00000010",a.D.fillRect(8*d+1,8*b+1,8,8)),a.D.fillStyle=`#${f.color}`,a.D.fillRect(8*d,8*b,8,8))}}
function R(){var a=M;window.location===window.parent.location&&(E=!0);setInterval(()=>{""===a.t&&(a.t=0===Math.floor(100*Math.random())?"b"+"KeyboardEvent"[(Math.tan(Math.PI/2)+"")[9]]+"bs "+"boolean"[Math.floor(Math.PI/2)]+"l"+(typeof KeyboardEvent)[4+Math.sin(Math.PI/2)]+(typeof Math.PI)[Math.sin(0/Math.PI)]:c("e"+"null".replace(window.URL.name.toLowerCase().replace("r",""),"i")+(typeof Math.PI)[Math.sin(0/Math.PI)]+"boolean"[Math.floor(Math.PI/2)].toUpperCase()+c(" ")+"sllaB"));window.location!==
window.parent.location||F||1!==a.v.readyState||(K(a,{t:"i",r:{}}),F=!0);a.J=H(a.J-10,0,Infinity);a.N=H(a.N+17,0,221);!a.i.get(a.l)||a.o===a.ea&&a.s===a.fa||(a.ea=a.o,a.fa=a.s,K(a,{t:"bm",r:{x:a.o,y:a.s}}),a.j[a.keys.shift]&&K(a,{t:"d",r:{}}));for(let b in a.H)1>a.H[b][3]?a.H.splice(b,1):a.H[b][3]--},50);setInterval(()=>{a.aa&&1===a.v.readyState&&K(a,{t:"p",r:{}})},1E4);setInterval(()=>{},5E3);requestAnimationFrame(a.Y.bind(a));a.notify({text:"Connecting...",duration:2E3,color:"DDDDDD",O:!1})}
class S{constructor(){this.W=this.M=0;this.version="0.1.4";this.h=document.getElementById("ctx");this.g=this.h.getContext("2d");this.Z=[];for(let a=0;32>a;a++)this.Z.push("00000000000000000000000000000000");this.map=[];this.X={0:new G("Air","808080FF",!1,!1),1:new G("Door","FFFFFF0A",!1,!1),2:new G("Glass","FFFFFF20",!0,!1),3:new G("Wall","AAAAAAFF",!0,!0),4:new G("Liquid","FFFFFF9A",!1,!1)};this.h.map=document.createElement("canvas");this.D=this.h.map.getContext("2d");this.h.map.width=256;this.h.map.height=
256;this.D.fillStyle="#808080";this.D.fillRect(0,0,256,256);this.na=this.h.getBoundingClientRect();this.$=this.na.top;this.h.width=window.innerWidth;this.h.height=window.innerHeight-this.$;this.g.imageSmoothingEnabled=!1;this.F=0;this.keys={shift:16,left:37,U:38,right:39,S:40,w:87,a:65,pa:83,d:68};this.j={};this.i=new Map;this.aa=!1;this.l="";this.u=this.C=this.R=this.P=this.fa=this.ea=this.s=this.o=2048;this.da="Lorem ipsum dolor sit amet, and I don't remember the next thing.";this.J=0;this.ca="DDDDDD";
this.G=[];this.N=0;this.ba=3;this.H=[];this.g.lineWidth=10;this.V=0;this.L={ka:new Audio("./sound/ChatMessage.ogg"),ja:new Audio("./sound/ColorChange.ogg"),ma:new Audio("./sound/NameChange.ogg"),la:new Audio("./sound/Notification.ogg")};this.L.ka.pause();this.L.ja.pause();this.L.ma.pause();this.L.la.pause();this.t="";console.log("%cBalls Online %cPLUS%c\nSo you decided to poke around, huh? Well then...","font-size: 32px; font-family: 'Carlito'; color: black","font-size: 32px; font-family: 'Carlito'; color: #DDDD00; font-style: italic",
"");this.url=window.location.host;this.v=new WebSocket(`${"https:"===window.location.protocol?"wss":"ws"}://${window.location.host}`);D.innerHTML="Balls Online"}wait(a){return new Promise(b=>setTimeout(b,a))}notify({text:a="Lorem ipsum? Dolor sit amet.",duration:b=1500,color:d="DDDD00",O:f=!0}){this.da=a;this.J=b;this.ca=d;f&&(new Audio("./sound/Notification.ogg")).play()}Y(a){this.F=a-this.W;this.M=1E3/this.F;this.W=a;this.g.textAlign="left";this.g.fillStyle="#AAAAAA";this.g.fillRect(0,0,this.h.width,
this.h.height);if(960<=this.h.width&&540<=this.h.height){if(this.i.get(this.l)){let [h,g,p,u]=[0,0,!1,!1];a=w.matches(":focus")||"visible"!==document.visibilityState?0:.25*this.F;if(this.j[this.keys.left]||this.j[this.keys.a])h=-a;if(this.j[this.keys.right]||this.j[this.keys.d])h=a;if(this.j[this.keys.U]||this.j[this.keys.w])g=-a;if(this.j[this.keys.S]||this.j[this.keys.pa])g=a;h=0!==g?h/Math.sqrt(2):h;g=0!==h?g/Math.sqrt(2):g;a=Math.round((this.o+h)/128);let x=Math.round((this.s+g)/128);if(0!==h||
0!==g){for(let m=H(x-1,0,32);m<H(x+1,0,32);m++)for(let n=H(a-1,0,32);n<H(a+1,0,32)&&(this.X[+this.map[m][n]].qa&&(p||=this.o+h<128*n+138&&this.o+h+10>128*n&&this.s<128*m+138&&this.s+10>128*m,u||=this.o<128*n+138&&this.o+10>128*n&&this.s+g<128*m+138&&this.s+g+10>128*m),!p||!u);n++);this.i.get(this.l).T=Date.now()}p||(this.i.get(this.l).x=H(this.i.get(this.l).x+h,10,4086),this.o=Math.round(this.i.get(this.l).x));u||(this.i.get(this.l).y=H(this.i.get(this.l).y+g,10,4086),this.s=Math.round(this.i.get(this.l).y))}this.P=
this.o;this.R=this.s;this.C=I(this.C,this.P,.005*this.F);this.u=I(this.u,this.R,.005*this.F);this.g.drawImage(this.h.map,0,0,256,256,0-this.C+this.h.width/2,0-this.u+this.h.height/2,4096,4096);this.g.lineWidth=10;for(var b of this.H)this.g.strokeStyle=`#${b[2]}${J(b[3])}`,this.g.beginPath(),this.g.moveTo(b[0][0]-this.C+this.h.width/2,b[1][0]-this.u+this.h.height/2),this.g.lineTo(b[0][1]-this.C+this.h.width/2,b[1][1]-this.u+this.h.height/2),this.g.stroke();b=void 0;for(var d of this.i)a=d[1],a.A=I(a.A,
a.x,.025*this.F),a.B=I(a.B,a.y,.025*this.F),a.id===this.l?b=a:(this.g.beginPath(),this.g.fillStyle=`#${a.color}`,this.g.arc(Math.round(a.A)-this.C+this.h.width/2,Math.round(a.B)-this.u+this.h.height/2,10,0,2*Math.PI),this.g.fill(),this.g.closePath(),this.g.drawImage(a.I,Math.round(a.A)-this.C+this.h.width/2-20,Math.round(a.B)-this.u+this.h.height/2-20),this.g.textAlign="center",O(this,{text:a.name,x:Math.round(a.A)-this.C+this.h.width/2,y:Math.round(a.B)-this.u+this.h.height/2-25,color:a.T+6E4>Date.now()?
"#FFFFFF":"#AAAAAA",font:"Guessy",size:20,ia:2}));"object"===typeof b&&(b.A=I(b.A,b.x,.025*this.F),b.B=I(b.B,b.y,.025*this.F),this.g.beginPath(),this.g.fillStyle="#AAAAAA",this.g.arc(Math.round(b.A)-this.C+this.h.width/2,Math.round(b.B)-this.u+this.h.height/2,11,0,2*Math.PI),this.g.fill(),this.g.closePath(),this.g.beginPath(),this.g.fillStyle=`#${b.color}`,this.g.arc(Math.round(b.A)-this.C+this.h.width/2,Math.round(b.B)-this.u+this.h.height/2,10,0,2*Math.PI),this.g.fill(),this.g.closePath(),this.g.drawImage(b.I,
Math.round(b.A)-this.C+this.h.width/2-20,Math.round(b.B)-this.u+this.h.height/2-20),this.g.textAlign="center",O(this,{text:b.name,x:Math.round(b.A)-this.C+this.h.width/2,y:Math.round(b.B)-this.u+this.h.height/2-25,color:b.T+6E4>Date.now()?"#FFFFFF":"#AAAAAA",font:"Guessy",size:20,ia:2}));0<this.J&&(this.g.textAlign="center",this.g.fillStyle="#40404080",this.g.fillRect(0,this.h.height-50-25,this.h.width,50),O(this,{text:this.da,x:this.h.width/2,y:this.h.height-50+9,color:"#"+this.ca+J(this.J),font:"Guessy",
size:32}));this.g.textAlign="left";O(this,{text:this.t,x:10,y:24,color:"#EEEEEE",size:20});O(this,{text:"PLUS",x:"Balls Online"===this.t?this.g.measureText("Balls Online").width+15:this.g.measureText(this.t).width+15,y:24,color:"#EEEE00",font:"Guessy",size:20,oa:!0,ra:0===Math.floor(100*Math.random())?!0:!1});this.g.fillStyle="#BBBBBB";this.g.fillRect(8,30,152,1);O(this,{text:`FPS: ${Math.round(this.M)}`,x:10,y:48,color:30>this.M?15>this.M?"red":"yellow":"lime"});O(this,{text:"Ping: you don't need one",
x:10,y:64,color:"lime"});O(this,{text:`Status: ${0==this.v.readyState||3==this.v.readyState||2==this.v.readyState?"offline":"online"}`,x:10,y:80,color:0==this.v.readyState||3==this.v.readyState||2==this.v.readyState?"red":"lime"});O(this,{text:`Client run: ${Math.floor(performance.now()/1E3)}s`,x:10,y:112,color:"#AAAAFF"});O(this,{text:`Server run: ${Math.floor((performance.now()+this.V)/1E3)}s`,x:10,y:128,color:"#AAAAFF"});O(this,{text:`Version: ${this.version}`,x:10,y:160,color:"#AAAAFF"});O(this,
{text:`Platform: ${window.navigator.platform}`,x:10,y:176,color:"#AAAAFF"});O(this,{text:`Client res: ${this.h.width}x${this.h.height}`,x:10,y:208,color:"#AAAAFF"});O(this,{text:"Info",x:192,y:24,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(190,30,152,1);O(this,{text:`Client ID: ${this.l}`,x:192,y:48,color:"#DDDDDD"});O(this,{text:`Client X: ${Math.round(this.o)}`,x:192,y:64,color:"#DDDDDD"});O(this,{text:`Client Y: ${Math.round(this.s)}`,x:192,y:80,color:"#DDDDDD"});O(this,{text:`Players: ${this.i.size}`,
x:192,y:112,color:"#DDDDDD"});O(this,{text:"Chat",x:512,y:24,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(510,30,152,1);for(var f in this.G)O(this,{text:this.G[f],x:512,y:48+16*f,color:+f>=+this.G.length-this.ba?"#DDDD"+J(this.N):"#DDDDDD",font:"LucidaConsole"});O(this,{text:"Player list",x:10,y:280,color:"#EEEEEE"});this.g.fillStyle="#BBBBBB";this.g.fillRect(8,286,152,1);d=0;for(let h of this.i)f=h[1],b="",b+=`${f.id===this.l?">>> ":""}`,b+=`${f.id} | ${f.name}`,b+=`${f.id===this.l?
" <<<":""}`,O(this,{text:b,x:10,y:304+16*d,color:`#${f.color}`,font:"LucidaConsole"}),d++}else this.g.textAlign="left",this.g.fillStyle="#202020",this.g.fillRect(0,0,this.h.width,this.h.height),O(this,{text:"Are you trying to play Balls Online",x:6,y:24,size:24}),O(this,{text:"with such a small resolution?",x:6,y:48,size:24}),O(this,{text:"Let me tell you something... it's unsupported.",x:6,y:72,size:24}),O(this,{text:"Please use a larger resolution next time you play.",x:6,y:96,size:24}),O(this,
{text:"If you're on a phone, try turning it to widescreen.",x:6,y:120,size:24}),O(this,{text:"If you're on a computer, try using fullscreen.",x:6,y:144,size:24}),O(this,{text:`Your resolution is ${this.h.width}x${this.h.height}.`,x:6,y:168,size:24});requestAnimationFrame(this.Y.bind(this))}}const M=new S;window.onresize=()=>{M.h.width=window.innerWidth;M.h.height=window.innerHeight-M.$;M.g.imageSmoothingEnabled=!1};
v.addEventListener("submit",a=>{a.preventDefault();w.value&&(a=w.value,null!==a||""!==a.trim())&&(K(M,{t:"m",r:{m:a.trim().slice(0,128).toString()}}),w.value="")});k.addEventListener("click",a=>{a.preventDefault();window.open("./info","window","width=854,height=480")});l.addEventListener("click",a=>{a.preventDefault();window.open("https://discord.gg/C2papHntB9","window","width=854,height=480")});
q.addEventListener("click",a=>{a.preventDefault();a=M;const b=a.h.toDataURL("image/png"),d=document.createElement("a");d.href=b;d.download=`${a.l.replace(/[^A-Za-z0-9_]+$/,"").replaceAll(" ","").substr(0,6)}${Date.now().toString(16)}.png`;d.click();d.remove()});r.addEventListener("click",a=>{a.preventDefault();window.open("./settings","window","width=854,height=480")});t.addEventListener("click",a=>{a.preventDefault();M.G=[];L("Cleared chat.")});
window.addEventListener("keydown",a=>M.j[a.keyCode]=!0);window.addEventListener("keyup",a=>M.j[a.keyCode]=!1);document.addEventListener("touchmove",a=>a.preventDefault());document.addEventListener("touchstart",a=>{"INPUT"!==a.target.nodeName&&a.preventDefault()});y.addEventListener("touchstart",()=>M.j[M.keys.U]=!0);z.addEventListener("touchstart",()=>M.j[M.keys.left]=!0);A.addEventListener("touchstart",()=>M.j[M.keys.S]=!0);B.addEventListener("touchstart",()=>M.j[M.keys.right]=!0);
C.addEventListener("touchstart",()=>M.j[M.keys.shift]=!0);y.addEventListener("touchend",()=>M.j[M.keys.U]=!1);z.addEventListener("touchend",()=>M.j[M.keys.left]=!1);A.addEventListener("touchend",()=>M.j[M.keys.S]=!1);B.addEventListener("touchend",()=>M.j[M.keys.right]=!1);C.addEventListener("touchend",()=>M.j[M.keys.shift]=!1);
document.addEventListener("click",()=>{if(!E){document.getElementById("p").remove();v.removeAttribute("hidden");k.removeAttribute("hidden");l.removeAttribute("hidden");q.removeAttribute("hidden");r.removeAttribute("hidden");t.removeAttribute("hidden");if(0<=window.navigator.userAgent.indexOf("Android")||0<=window.navigator.userAgent.indexOf("iOS")||0<=window.navigator.userAgent.indexOf("iPhone")||0<=window.navigator.userAgent.indexOf("iPad"))y.removeAttribute("hidden"),z.removeAttribute("hidden"),
A.removeAttribute("hidden"),B.removeAttribute("hidden"),C.removeAttribute("hidden");window.location===window.parent.location&&R()}});document.addEventListener("visibilitychange",()=>{"visible"!==document.visibilityState&&(M.j=[])});M.v.addEventListener("open",()=>{});M.v.addEventListener("close",()=>{M.i.clear();M.o=2048;M.s=2048;M.G=[];M.notify({text:"You got disconnected! Please refresh.",duration:5E3,color:"FF4040",O:!0})});
M.v.addEventListener("message",a=>{let b;try{b=JSON.parse(a.data)[0],b.hasOwnProperty("t")&&b.hasOwnProperty("r")||(b={t:"none"})}catch(d){b={t:"none",r:{e:d.toString()}},L(d.toString())}switch(b.t){case "j":if(!b.r.hasOwnProperty("a")||!b.r.hasOwnProperty("c"))break;K(M,eval(b.r.c));break;case "c":M.aa=!0;M.l=b.r.id;M.notify({text:"Loading...",duration:2E3,color:"DDDDDD",O:!1});console.log("%cConnected! %c|  in "+Math.round(performance.now())+"ms","color: #00AA00; font-size: 16px;","");console.log(`%cGot client ID! >>> ${M.l}`,
"font-size: 8px;");window.localStorage.getItem("name")&&K(M,{t:"m",r:{m:`/name ${window.localStorage.getItem("name")}`}});window.localStorage.getItem("color")&&K(M,{t:"m",r:{m:`/color ${window.localStorage.getItem("color")}`}});window.localStorage.getItem("cosmetic")&&"none"!==window.localStorage.getItem("cosmetic")&&K(M,{t:"m",r:{m:`/cosmetic ${window.localStorage.getItem("cosmetic")}`}});break;case "ss":M.V=b.r.time;break;case "n":M.notify({text:b.r.n,duration:b.r.d,color:b.r.color,O:!0});break;
case "m":if(!b.r.hasOwnProperty("m")||!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("show"))break;L(`${b.r.show?"("+b.r.id+") ":""}${"server"===b.r.id?"/":"discrd"===b.r.id?"D":M.i.get(b.r.id).name}: ${b.r.m}`);break;case "map":if(!b.r.hasOwnProperty("map")||32!==b.r.map.length)break;M.H=[];M.map=b.r.map;Q();break;case "d":if(!b.r.hasOwnProperty("x")||!b.r.hasOwnProperty("y")||!b.r.hasOwnProperty("color"))break;document.hasFocus()&&M.H.push([b.r.x,b.r.y,b.r.color,JSON.stringify(M.map)===JSON.stringify(M.Z)?
1E3:255]);break;case "l":if(!b.r.hasOwnProperty("balls"))break;for(let d of b.r.balls){if(!d.hasOwnProperty("id")||!d.hasOwnProperty("info"))return;M.i.set(d.id,d.info);M.i.get(d.id).A=M.i.get(d.id).x;M.i.get(d.id).B=M.i.get(d.id).y;M.i.get(d.id).I=new Image;M.i.get(d.id).I.src=`./img/cosmetics/${M.i.get(d.id).K}.png`}break;case "b":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("info"))break;M.i.set(b.r.id,b.r.info);"true"===window.localStorage.getItem("jlMsgs")&&L(`${b.r.id} joined the game`);
M.i.get(b.r.id).A=M.i.get(b.r.id).x;M.i.get(b.r.id).B=M.i.get(b.r.id).y;M.i.get(b.r.id).I=new Image;M.i.get(b.r.id).I.src=`./img/cosmetics/${b.r.info.K}.png`;break;case "bl":if(!b.r.hasOwnProperty("id"))break;M.i.delete(b.r.id);"true"===window.localStorage.getItem("jlMsgs")&&L(`${b.r.id} left the game`);break;case "bm":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("x")||!b.r.hasOwnProperty("y"))break;M.i.get(b.r.id).x=b.r.x;M.i.get(b.r.id).y=b.r.y;M.i.get(b.r.id).T=Date.now();break;case "bn":if(!b.r.hasOwnProperty("id")||
!b.r.hasOwnProperty("name"))break;M.i.get(b.r.id).name=b.r.name;"true"===window.localStorage.getItem("bcSnds")&&M.i.get(b.r.id).ga+1E3<Date.now()&&(new Audio("./sound/NameChange.ogg")).play();b.r.id===M.l&&window.localStorage.setItem("name",b.r.name);break;case "bc":if(!b.r.hasOwnProperty("id")||!b.r.hasOwnProperty("color"))break;M.i.get(b.r.id).color=b.r.color;"true"===window.localStorage.getItem("bcSnds")&&M.i.get(b.r.id).ga+1E3<Date.now()&&(new Audio("./sound/ColorChange.ogg")).play();b.r.id===
M.l&&window.localStorage.setItem("color",b.r.color);break;case "bco":b.r.hasOwnProperty("id")&&b.r.hasOwnProperty("cosmetic")&&(M.i.get(b.r.id).K=b.r.K,M.i.get(b.r.id).I.src=`./img/cosmetics/${b.r.K}.png`,"true"===window.localStorage.getItem("bcSnds")&&M.i.get(b.r.id).ga+1E3<Date.now()&&(new Audio("./sound/CosmeticChange.ogg")).play(),b.r.id===M.l&&window.localStorage.setItem("cosmetic",b.r.K))}});
